/* tslint:disable */
/* eslint-disable */
/*
WebLink API

For documentation about this API, please visit https://developer.paylocity.com/integrations/reference/weblink-overview

The version of the OpenAPI document: v2
Contact: webservices@paylocity.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
import { setOAuthToObject } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { ModelError } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * CompanySpecificSchemaApi - axios parameter creator
 * @export
 */
export const CompanySpecificSchemaApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * The company-specific Open API endpoint allows the client to GET an Open API document for the Paylocity API that is customized with company-specific resource schemas. These customized resource schemas define certain properties as enumerations of pre-defined values that correspond to the company\'s setup with Paylocity Payroll/HR solution. The customized schemas also indicate which properties are required by the company within Paylocity Payroll/HR solution.<br  />To learn more about Open API, click [here](https://www.openapis.org/)
         * @summary Get Company-Specific Open API Documentation
         * @param {string} companyId The Paylocity Company Identifier. This is the unique value provided by Paylocity to each specific Payroll Entity.                  **Allowable Values:**                  9 char max
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOpenApiDoc: async (companyId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'companyId' is not null or undefined
            assertParamExists('getOpenApiDoc', 'companyId', companyId)
            const localVarPath = `/v2/companies/{companyId}/openapi`
                .replace(`{${"companyId"}}`, encodeURIComponent(String(companyId !== undefined ? companyId : `-companyId-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication paylocity_auth required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "paylocity_auth", ["WebLinkAPI"], configuration)

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/v2/companies/{companyId}/openapi',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CompanySpecificSchemaApi - functional programming interface
 * @export
 */
export const CompanySpecificSchemaApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CompanySpecificSchemaApiAxiosParamCreator(configuration)
    return {
        /**
         * The company-specific Open API endpoint allows the client to GET an Open API document for the Paylocity API that is customized with company-specific resource schemas. These customized resource schemas define certain properties as enumerations of pre-defined values that correspond to the company\'s setup with Paylocity Payroll/HR solution. The customized schemas also indicate which properties are required by the company within Paylocity Payroll/HR solution.<br  />To learn more about Open API, click [here](https://www.openapis.org/)
         * @summary Get Company-Specific Open API Documentation
         * @param {CompanySpecificSchemaApiGetOpenApiDocRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getOpenApiDoc(requestParameters: CompanySpecificSchemaApiGetOpenApiDocRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getOpenApiDoc(requestParameters.companyId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * CompanySpecificSchemaApi - factory interface
 * @export
 */
export const CompanySpecificSchemaApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CompanySpecificSchemaApiFp(configuration)
    return {
        /**
         * The company-specific Open API endpoint allows the client to GET an Open API document for the Paylocity API that is customized with company-specific resource schemas. These customized resource schemas define certain properties as enumerations of pre-defined values that correspond to the company\'s setup with Paylocity Payroll/HR solution. The customized schemas also indicate which properties are required by the company within Paylocity Payroll/HR solution.<br  />To learn more about Open API, click [here](https://www.openapis.org/)
         * @summary Get Company-Specific Open API Documentation
         * @param {CompanySpecificSchemaApiGetOpenApiDocRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOpenApiDoc(requestParameters: CompanySpecificSchemaApiGetOpenApiDocRequest, options?: AxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.getOpenApiDoc(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getOpenApiDoc operation in CompanySpecificSchemaApi.
 * @export
 * @interface CompanySpecificSchemaApiGetOpenApiDocRequest
 */
export type CompanySpecificSchemaApiGetOpenApiDocRequest = {
    
    /**
    * The Paylocity Company Identifier. This is the unique value provided by Paylocity to each specific Payroll Entity.                  **Allowable Values:**                  9 char max
    * @type {string}
    * @memberof CompanySpecificSchemaApiGetOpenApiDoc
    */
    readonly companyId: string
    
}

/**
 * CompanySpecificSchemaApiGenerated - object-oriented interface
 * @export
 * @class CompanySpecificSchemaApiGenerated
 * @extends {BaseAPI}
 */
export class CompanySpecificSchemaApiGenerated extends BaseAPI {
    /**
     * The company-specific Open API endpoint allows the client to GET an Open API document for the Paylocity API that is customized with company-specific resource schemas. These customized resource schemas define certain properties as enumerations of pre-defined values that correspond to the company\'s setup with Paylocity Payroll/HR solution. The customized schemas also indicate which properties are required by the company within Paylocity Payroll/HR solution.<br  />To learn more about Open API, click [here](https://www.openapis.org/)
     * @summary Get Company-Specific Open API Documentation
     * @param {CompanySpecificSchemaApiGetOpenApiDocRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CompanySpecificSchemaApiGenerated
     */
    public getOpenApiDoc(requestParameters: CompanySpecificSchemaApiGetOpenApiDocRequest, options?: AxiosRequestConfig) {
        return CompanySpecificSchemaApiFp(this.configuration).getOpenApiDoc(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
