/* tslint:disable */
/* eslint-disable */
/*
WebLink API

For documentation about this API, please visit https://developer.paylocity.com/integrations/reference/weblink-overview

The version of the OpenAPI document: v2
Contact: webservices@paylocity.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
import { setOAuthToObject } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { BenefitSetup } from '../models';
// @ts-ignore
import { ModelError } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * EmployeeBenefitSetupApi - axios parameter creator
 * @export
 */
export const EmployeeBenefitSetupApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Sends new or updated employee benefit setup information directly to Paylocity Payroll/HR solution.
         * @summary Add/update employee\'s benefit setup
         * @param {string} companyId The Paylocity Company Identifier. This is the unique value provided by Paylocity to each specific Payroll Entity.                  **Allowable Values:**                  9 char max
         * @param {string} employeeId The Paylocity Employee ID. This is a unique value per Paylocity Company ID.  **Allowable Values:**  10 char max
         * @param {BenefitSetup} json BenefitSetup Model
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addOrUpdateBenefitSetup: async (companyId: string, employeeId: string, json: BenefitSetup, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'companyId' is not null or undefined
            assertParamExists('addOrUpdateBenefitSetup', 'companyId', companyId)
            // verify required parameter 'employeeId' is not null or undefined
            assertParamExists('addOrUpdateBenefitSetup', 'employeeId', employeeId)
            // verify required parameter 'json' is not null or undefined
            assertParamExists('addOrUpdateBenefitSetup', 'json', json)
            const localVarPath = `/v2/companies/{companyId}/employees/{employeeId}/benefitSetup`
                .replace(`{${"companyId"}}`, encodeURIComponent(String(companyId !== undefined ? companyId : `-companyId-`)))
                .replace(`{${"employeeId"}}`, encodeURIComponent(String(employeeId !== undefined ? employeeId : `-employeeId-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication paylocity_auth required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "paylocity_auth", ["WebLinkAPI"], configuration)

    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: json,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/v2/companies/{companyId}/employees/{employeeId}/benefitSetup',
                httpMethod: 'PUT'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(json, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * EmployeeBenefitSetupApi - functional programming interface
 * @export
 */
export const EmployeeBenefitSetupApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = EmployeeBenefitSetupApiAxiosParamCreator(configuration)
    return {
        /**
         * Sends new or updated employee benefit setup information directly to Paylocity Payroll/HR solution.
         * @summary Add/update employee\'s benefit setup
         * @param {EmployeeBenefitSetupApiAddOrUpdateBenefitSetupRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addOrUpdateBenefitSetup(requestParameters: EmployeeBenefitSetupApiAddOrUpdateBenefitSetupRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const json: BenefitSetup = {
                benefitClass: requestParameters.benefitClass,
                benefitClassEffectiveDate: requestParameters.benefitClassEffectiveDate,
                benefitSalary: requestParameters.benefitSalary,
                benefitSalaryEffectiveDate: requestParameters.benefitSalaryEffectiveDate,
                doNotApplyAdministrativePeriod: requestParameters.doNotApplyAdministrativePeriod,
                isMeasureAcaEligibility: requestParameters.isMeasureAcaEligibility
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.addOrUpdateBenefitSetup(requestParameters.companyId, requestParameters.employeeId, json, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * EmployeeBenefitSetupApi - factory interface
 * @export
 */
export const EmployeeBenefitSetupApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = EmployeeBenefitSetupApiFp(configuration)
    return {
        /**
         * Sends new or updated employee benefit setup information directly to Paylocity Payroll/HR solution.
         * @summary Add/update employee\'s benefit setup
         * @param {EmployeeBenefitSetupApiAddOrUpdateBenefitSetupRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addOrUpdateBenefitSetup(requestParameters: EmployeeBenefitSetupApiAddOrUpdateBenefitSetupRequest, options?: AxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.addOrUpdateBenefitSetup(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for addOrUpdateBenefitSetup operation in EmployeeBenefitSetupApi.
 * @export
 * @interface EmployeeBenefitSetupApiAddOrUpdateBenefitSetupRequest
 */
export type EmployeeBenefitSetupApiAddOrUpdateBenefitSetupRequest = {
    
    /**
    * The Paylocity Company Identifier. This is the unique value provided by Paylocity to each specific Payroll Entity.                  **Allowable Values:**                  9 char max
    * @type {string}
    * @memberof EmployeeBenefitSetupApiAddOrUpdateBenefitSetup
    */
    readonly companyId: string
    
    /**
    * The Paylocity Employee ID. This is a unique value per Paylocity Company ID.  **Allowable Values:**  10 char max
    * @type {string}
    * @memberof EmployeeBenefitSetupApiAddOrUpdateBenefitSetup
    */
    readonly employeeId: string
    
} & BenefitSetup

/**
 * EmployeeBenefitSetupApiGenerated - object-oriented interface
 * @export
 * @class EmployeeBenefitSetupApiGenerated
 * @extends {BaseAPI}
 */
export class EmployeeBenefitSetupApiGenerated extends BaseAPI {
    /**
     * Sends new or updated employee benefit setup information directly to Paylocity Payroll/HR solution.
     * @summary Add/update employee\'s benefit setup
     * @param {EmployeeBenefitSetupApiAddOrUpdateBenefitSetupRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EmployeeBenefitSetupApiGenerated
     */
    public addOrUpdateBenefitSetup(requestParameters: EmployeeBenefitSetupApiAddOrUpdateBenefitSetupRequest, options?: AxiosRequestConfig) {
        return EmployeeBenefitSetupApiFp(this.configuration).addOrUpdateBenefitSetup(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
