/* tslint:disable */
/* eslint-disable */
/*
WebLink API

For documentation about this API, please visit https://developer.paylocity.com/integrations/reference/weblink-overview

The version of the OpenAPI document: v2
Contact: webservices@paylocity.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
import { setOAuthToObject } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { LocalTax } from '../models';
// @ts-ignore
import { ModelError } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * LocalTaxesApi - axios parameter creator
 * @export
 */
export const LocalTaxesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Sends new employee local tax information directly to Paylocity Payroll/HR solution.
         * @summary Add new local tax
         * @param {string} companyId The Paylocity Company Identifier. This is the unique value provided by Paylocity to each specific Payroll Entity.                  **Allowable Values:**                  9 char max
         * @param {string} employeeId The Paylocity Employee ID. This is a unique value per Paylocity Company ID.  **Allowable Values:**  10 char max
         * @param {LocalTax} json LocalTax Model
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addNewTax: async (companyId: string, employeeId: string, json: LocalTax, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'companyId' is not null or undefined
            assertParamExists('addNewTax', 'companyId', companyId)
            // verify required parameter 'employeeId' is not null or undefined
            assertParamExists('addNewTax', 'employeeId', employeeId)
            // verify required parameter 'json' is not null or undefined
            assertParamExists('addNewTax', 'json', json)
            const localVarPath = `/v2/companies/{companyId}/employees/{employeeId}/localTaxes`
                .replace(`{${"companyId"}}`, encodeURIComponent(String(companyId !== undefined ? companyId : `-companyId-`)))
                .replace(`{${"employeeId"}}`, encodeURIComponent(String(employeeId !== undefined ? employeeId : `-employeeId-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication paylocity_auth required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "paylocity_auth", ["WebLinkAPI"], configuration)

    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: json,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/v2/companies/{companyId}/employees/{employeeId}/localTaxes',
                httpMethod: 'POST'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(json, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Delete local tax by tax code
         * @summary Delete local tax by tax code
         * @param {string} companyId The Paylocity Company Identifier. This is the unique value provided by Paylocity to each specific Payroll Entity.                  **Allowable Values:**                  9 char max
         * @param {string} employeeId The Paylocity Employee ID. This is a unique value per Paylocity Company ID.  **Allowable Values:**  10 char max
         * @param {string} taxCode Tax Code
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteByTaxCode: async (companyId: string, employeeId: string, taxCode: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'companyId' is not null or undefined
            assertParamExists('deleteByTaxCode', 'companyId', companyId)
            // verify required parameter 'employeeId' is not null or undefined
            assertParamExists('deleteByTaxCode', 'employeeId', employeeId)
            // verify required parameter 'taxCode' is not null or undefined
            assertParamExists('deleteByTaxCode', 'taxCode', taxCode)
            const localVarPath = `/v2/companies/{companyId}/employees/{employeeId}/localTaxes/{taxCode}`
                .replace(`{${"companyId"}}`, encodeURIComponent(String(companyId !== undefined ? companyId : `-companyId-`)))
                .replace(`{${"employeeId"}}`, encodeURIComponent(String(employeeId !== undefined ? employeeId : `-employeeId-`)))
                .replace(`{${"taxCode"}}`, encodeURIComponent(String(taxCode !== undefined ? taxCode : `-taxCode-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication paylocity_auth required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "paylocity_auth", ["WebLinkAPI"], configuration)

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/v2/companies/{companyId}/employees/{employeeId}/localTaxes/{taxCode}',
                httpMethod: 'DELETE'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns all local taxes for the selected employee.
         * @summary Get all local taxes
         * @param {string} companyId The Paylocity Company Identifier. This is the unique value provided by Paylocity to each specific Payroll Entity.                  **Allowable Values:**                  9 char max
         * @param {string} employeeId The Paylocity Employee ID. This is a unique value per Paylocity Company ID.  **Allowable Values:**  10 char max
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllForEmployee: async (companyId: string, employeeId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'companyId' is not null or undefined
            assertParamExists('getAllForEmployee', 'companyId', companyId)
            // verify required parameter 'employeeId' is not null or undefined
            assertParamExists('getAllForEmployee', 'employeeId', employeeId)
            const localVarPath = `/v2/companies/{companyId}/employees/{employeeId}/localTaxes`
                .replace(`{${"companyId"}}`, encodeURIComponent(String(companyId !== undefined ? companyId : `-companyId-`)))
                .replace(`{${"employeeId"}}`, encodeURIComponent(String(employeeId !== undefined ? employeeId : `-employeeId-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication paylocity_auth required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "paylocity_auth", ["WebLinkAPI"], configuration)

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/v2/companies/{companyId}/employees/{employeeId}/localTaxes',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns all local taxes with the provided tax code for the selected employee.
         * @summary Get local taxes by tax code
         * @param {string} companyId The Paylocity Company Identifier. This is the unique value provided by Paylocity to each specific Payroll Entity.                  **Allowable Values:**                  9 char max
         * @param {string} employeeId The Paylocity Employee ID. This is a unique value per Paylocity Company ID.  **Allowable Values:**  10 char max
         * @param {string} taxCode Tax Code
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getByTaxCode: async (companyId: string, employeeId: string, taxCode: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'companyId' is not null or undefined
            assertParamExists('getByTaxCode', 'companyId', companyId)
            // verify required parameter 'employeeId' is not null or undefined
            assertParamExists('getByTaxCode', 'employeeId', employeeId)
            // verify required parameter 'taxCode' is not null or undefined
            assertParamExists('getByTaxCode', 'taxCode', taxCode)
            const localVarPath = `/v2/companies/{companyId}/employees/{employeeId}/localTaxes/{taxCode}`
                .replace(`{${"companyId"}}`, encodeURIComponent(String(companyId !== undefined ? companyId : `-companyId-`)))
                .replace(`{${"employeeId"}}`, encodeURIComponent(String(employeeId !== undefined ? employeeId : `-employeeId-`)))
                .replace(`{${"taxCode"}}`, encodeURIComponent(String(taxCode !== undefined ? taxCode : `-taxCode-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication paylocity_auth required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "paylocity_auth", ["WebLinkAPI"], configuration)

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/v2/companies/{companyId}/employees/{employeeId}/localTaxes/{taxCode}',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * LocalTaxesApi - functional programming interface
 * @export
 */
export const LocalTaxesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = LocalTaxesApiAxiosParamCreator(configuration)
    return {
        /**
         * Sends new employee local tax information directly to Paylocity Payroll/HR solution.
         * @summary Add new local tax
         * @param {LocalTaxesApiAddNewTaxRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addNewTax(requestParameters: LocalTaxesApiAddNewTaxRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const json: LocalTax = {
                exemptions: requestParameters.exemptions,
                exemptions2: requestParameters.exemptions2,
                filingStatus: requestParameters.filingStatus,
                residentPSD: requestParameters.residentPSD,
                taxCode: requestParameters.taxCode,
                workPSD: requestParameters.workPSD
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.addNewTax(requestParameters.companyId, requestParameters.employeeId, json, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Delete local tax by tax code
         * @summary Delete local tax by tax code
         * @param {LocalTaxesApiDeleteByTaxCodeRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteByTaxCode(requestParameters: LocalTaxesApiDeleteByTaxCodeRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteByTaxCode(requestParameters.companyId, requestParameters.employeeId, requestParameters.taxCode, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Returns all local taxes for the selected employee.
         * @summary Get all local taxes
         * @param {LocalTaxesApiGetAllForEmployeeRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllForEmployee(requestParameters: LocalTaxesApiGetAllForEmployeeRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<LocalTax>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllForEmployee(requestParameters.companyId, requestParameters.employeeId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Returns all local taxes with the provided tax code for the selected employee.
         * @summary Get local taxes by tax code
         * @param {LocalTaxesApiGetByTaxCodeRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getByTaxCode(requestParameters: LocalTaxesApiGetByTaxCodeRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<LocalTax>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getByTaxCode(requestParameters.companyId, requestParameters.employeeId, requestParameters.taxCode, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * LocalTaxesApi - factory interface
 * @export
 */
export const LocalTaxesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = LocalTaxesApiFp(configuration)
    return {
        /**
         * Sends new employee local tax information directly to Paylocity Payroll/HR solution.
         * @summary Add new local tax
         * @param {LocalTaxesApiAddNewTaxRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addNewTax(requestParameters: LocalTaxesApiAddNewTaxRequest, options?: AxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.addNewTax(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Delete local tax by tax code
         * @summary Delete local tax by tax code
         * @param {LocalTaxesApiDeleteByTaxCodeRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteByTaxCode(requestParameters: LocalTaxesApiDeleteByTaxCodeRequest, options?: AxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteByTaxCode(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns all local taxes for the selected employee.
         * @summary Get all local taxes
         * @param {LocalTaxesApiGetAllForEmployeeRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllForEmployee(requestParameters: LocalTaxesApiGetAllForEmployeeRequest, options?: AxiosRequestConfig): AxiosPromise<Array<LocalTax>> {
            return localVarFp.getAllForEmployee(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns all local taxes with the provided tax code for the selected employee.
         * @summary Get local taxes by tax code
         * @param {LocalTaxesApiGetByTaxCodeRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getByTaxCode(requestParameters: LocalTaxesApiGetByTaxCodeRequest, options?: AxiosRequestConfig): AxiosPromise<Array<LocalTax>> {
            return localVarFp.getByTaxCode(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for addNewTax operation in LocalTaxesApi.
 * @export
 * @interface LocalTaxesApiAddNewTaxRequest
 */
export type LocalTaxesApiAddNewTaxRequest = {
    
    /**
    * The Paylocity Company Identifier. This is the unique value provided by Paylocity to each specific Payroll Entity.                  **Allowable Values:**                  9 char max
    * @type {string}
    * @memberof LocalTaxesApiAddNewTax
    */
    readonly companyId: string
    
    /**
    * The Paylocity Employee ID. This is a unique value per Paylocity Company ID.  **Allowable Values:**  10 char max
    * @type {string}
    * @memberof LocalTaxesApiAddNewTax
    */
    readonly employeeId: string
    
} & LocalTax

/**
 * Request parameters for deleteByTaxCode operation in LocalTaxesApi.
 * @export
 * @interface LocalTaxesApiDeleteByTaxCodeRequest
 */
export type LocalTaxesApiDeleteByTaxCodeRequest = {
    
    /**
    * The Paylocity Company Identifier. This is the unique value provided by Paylocity to each specific Payroll Entity.                  **Allowable Values:**                  9 char max
    * @type {string}
    * @memberof LocalTaxesApiDeleteByTaxCode
    */
    readonly companyId: string
    
    /**
    * The Paylocity Employee ID. This is a unique value per Paylocity Company ID.  **Allowable Values:**  10 char max
    * @type {string}
    * @memberof LocalTaxesApiDeleteByTaxCode
    */
    readonly employeeId: string
    
    /**
    * Tax Code
    * @type {string}
    * @memberof LocalTaxesApiDeleteByTaxCode
    */
    readonly taxCode: string
    
}

/**
 * Request parameters for getAllForEmployee operation in LocalTaxesApi.
 * @export
 * @interface LocalTaxesApiGetAllForEmployeeRequest
 */
export type LocalTaxesApiGetAllForEmployeeRequest = {
    
    /**
    * The Paylocity Company Identifier. This is the unique value provided by Paylocity to each specific Payroll Entity.                  **Allowable Values:**                  9 char max
    * @type {string}
    * @memberof LocalTaxesApiGetAllForEmployee
    */
    readonly companyId: string
    
    /**
    * The Paylocity Employee ID. This is a unique value per Paylocity Company ID.  **Allowable Values:**  10 char max
    * @type {string}
    * @memberof LocalTaxesApiGetAllForEmployee
    */
    readonly employeeId: string
    
}

/**
 * Request parameters for getByTaxCode operation in LocalTaxesApi.
 * @export
 * @interface LocalTaxesApiGetByTaxCodeRequest
 */
export type LocalTaxesApiGetByTaxCodeRequest = {
    
    /**
    * The Paylocity Company Identifier. This is the unique value provided by Paylocity to each specific Payroll Entity.                  **Allowable Values:**                  9 char max
    * @type {string}
    * @memberof LocalTaxesApiGetByTaxCode
    */
    readonly companyId: string
    
    /**
    * The Paylocity Employee ID. This is a unique value per Paylocity Company ID.  **Allowable Values:**  10 char max
    * @type {string}
    * @memberof LocalTaxesApiGetByTaxCode
    */
    readonly employeeId: string
    
    /**
    * Tax Code
    * @type {string}
    * @memberof LocalTaxesApiGetByTaxCode
    */
    readonly taxCode: string
    
}

/**
 * LocalTaxesApiGenerated - object-oriented interface
 * @export
 * @class LocalTaxesApiGenerated
 * @extends {BaseAPI}
 */
export class LocalTaxesApiGenerated extends BaseAPI {
    /**
     * Sends new employee local tax information directly to Paylocity Payroll/HR solution.
     * @summary Add new local tax
     * @param {LocalTaxesApiAddNewTaxRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LocalTaxesApiGenerated
     */
    public addNewTax(requestParameters: LocalTaxesApiAddNewTaxRequest, options?: AxiosRequestConfig) {
        return LocalTaxesApiFp(this.configuration).addNewTax(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Delete local tax by tax code
     * @summary Delete local tax by tax code
     * @param {LocalTaxesApiDeleteByTaxCodeRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LocalTaxesApiGenerated
     */
    public deleteByTaxCode(requestParameters: LocalTaxesApiDeleteByTaxCodeRequest, options?: AxiosRequestConfig) {
        return LocalTaxesApiFp(this.configuration).deleteByTaxCode(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns all local taxes for the selected employee.
     * @summary Get all local taxes
     * @param {LocalTaxesApiGetAllForEmployeeRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LocalTaxesApiGenerated
     */
    public getAllForEmployee(requestParameters: LocalTaxesApiGetAllForEmployeeRequest, options?: AxiosRequestConfig) {
        return LocalTaxesApiFp(this.configuration).getAllForEmployee(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns all local taxes with the provided tax code for the selected employee.
     * @summary Get local taxes by tax code
     * @param {LocalTaxesApiGetByTaxCodeRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LocalTaxesApiGenerated
     */
    public getByTaxCode(requestParameters: LocalTaxesApiGetByTaxCodeRequest, options?: AxiosRequestConfig) {
        return LocalTaxesApiFp(this.configuration).getByTaxCode(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
