/* tslint:disable */
/* eslint-disable */
/*
WebLink API

For documentation about this API, please visit https://developer.paylocity.com/integrations/reference/weblink-overview

The version of the OpenAPI document: v2
Contact: webservices@paylocity.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
import { setOAuthToObject } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { ModelError } from '../models';
// @ts-ignore
import { SensitiveData } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * SensitiveDataApi - axios parameter creator
 * @export
 */
export const SensitiveDataApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Sends new or updated employee sensitive data information directly to Paylocity Payroll/HR solution.
         * @summary Add/update sensitive data
         * @param {string} companyId The Paylocity Company Identifier. This is the unique value provided by Paylocity to each specific Payroll Entity.                  **Allowable Values:**                  9 char max
         * @param {string} employeeId The Paylocity Employee ID. This is a unique value per Paylocity Company ID.  **Allowable Values:**  10 char max
         * @param {SensitiveData} json Sensitive Data Model
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addOrUpdateEmployeeSensitiveData: async (companyId: string, employeeId: string, json: SensitiveData, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'companyId' is not null or undefined
            assertParamExists('addOrUpdateEmployeeSensitiveData', 'companyId', companyId)
            // verify required parameter 'employeeId' is not null or undefined
            assertParamExists('addOrUpdateEmployeeSensitiveData', 'employeeId', employeeId)
            // verify required parameter 'json' is not null or undefined
            assertParamExists('addOrUpdateEmployeeSensitiveData', 'json', json)
            const localVarPath = `/v2/companies/{companyId}/employees/{employeeId}/sensitivedata`
                .replace(`{${"companyId"}}`, encodeURIComponent(String(companyId !== undefined ? companyId : `-companyId-`)))
                .replace(`{${"employeeId"}}`, encodeURIComponent(String(employeeId !== undefined ? employeeId : `-employeeId-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication paylocity_auth required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "paylocity_auth", ["WebLinkAPI"], configuration)

    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: json,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/v2/companies/{companyId}/employees/{employeeId}/sensitivedata',
                httpMethod: 'PUT'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(json, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Gets employee sensitive data information directly from Paylocity Payroll/HR solution.
         * @summary Get sensitive data
         * @param {string} companyId The Paylocity Company Identifier. This is the unique value provided by Paylocity to each specific Payroll Entity.                  **Allowable Values:**                  9 char max
         * @param {string} employeeId The Paylocity Employee ID. This is a unique value per Paylocity Company ID.  **Allowable Values:**  10 char max
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEmployeeSensitiveData: async (companyId: string, employeeId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'companyId' is not null or undefined
            assertParamExists('getEmployeeSensitiveData', 'companyId', companyId)
            // verify required parameter 'employeeId' is not null or undefined
            assertParamExists('getEmployeeSensitiveData', 'employeeId', employeeId)
            const localVarPath = `/v2/companies/{companyId}/employees/{employeeId}/sensitivedata`
                .replace(`{${"companyId"}}`, encodeURIComponent(String(companyId !== undefined ? companyId : `-companyId-`)))
                .replace(`{${"employeeId"}}`, encodeURIComponent(String(employeeId !== undefined ? employeeId : `-employeeId-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication paylocity_auth required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "paylocity_auth", ["WebLinkAPI"], configuration)

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/v2/companies/{companyId}/employees/{employeeId}/sensitivedata',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SensitiveDataApi - functional programming interface
 * @export
 */
export const SensitiveDataApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SensitiveDataApiAxiosParamCreator(configuration)
    return {
        /**
         * Sends new or updated employee sensitive data information directly to Paylocity Payroll/HR solution.
         * @summary Add/update sensitive data
         * @param {SensitiveDataApiAddOrUpdateEmployeeSensitiveDataRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addOrUpdateEmployeeSensitiveData(requestParameters: SensitiveDataApiAddOrUpdateEmployeeSensitiveDataRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const json: SensitiveData = {
                disability: requestParameters.disability,
                ethnicity: requestParameters.ethnicity,
                gender: requestParameters.gender,
                veteran: requestParameters.veteran
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.addOrUpdateEmployeeSensitiveData(requestParameters.companyId, requestParameters.employeeId, json, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Gets employee sensitive data information directly from Paylocity Payroll/HR solution.
         * @summary Get sensitive data
         * @param {SensitiveDataApiGetEmployeeSensitiveDataRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getEmployeeSensitiveData(requestParameters: SensitiveDataApiGetEmployeeSensitiveDataRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<SensitiveData>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getEmployeeSensitiveData(requestParameters.companyId, requestParameters.employeeId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * SensitiveDataApi - factory interface
 * @export
 */
export const SensitiveDataApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SensitiveDataApiFp(configuration)
    return {
        /**
         * Sends new or updated employee sensitive data information directly to Paylocity Payroll/HR solution.
         * @summary Add/update sensitive data
         * @param {SensitiveDataApiAddOrUpdateEmployeeSensitiveDataRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addOrUpdateEmployeeSensitiveData(requestParameters: SensitiveDataApiAddOrUpdateEmployeeSensitiveDataRequest, options?: AxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.addOrUpdateEmployeeSensitiveData(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Gets employee sensitive data information directly from Paylocity Payroll/HR solution.
         * @summary Get sensitive data
         * @param {SensitiveDataApiGetEmployeeSensitiveDataRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEmployeeSensitiveData(requestParameters: SensitiveDataApiGetEmployeeSensitiveDataRequest, options?: AxiosRequestConfig): AxiosPromise<Array<SensitiveData>> {
            return localVarFp.getEmployeeSensitiveData(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for addOrUpdateEmployeeSensitiveData operation in SensitiveDataApi.
 * @export
 * @interface SensitiveDataApiAddOrUpdateEmployeeSensitiveDataRequest
 */
export type SensitiveDataApiAddOrUpdateEmployeeSensitiveDataRequest = {
    
    /**
    * The Paylocity Company Identifier. This is the unique value provided by Paylocity to each specific Payroll Entity.                  **Allowable Values:**                  9 char max
    * @type {string}
    * @memberof SensitiveDataApiAddOrUpdateEmployeeSensitiveData
    */
    readonly companyId: string
    
    /**
    * The Paylocity Employee ID. This is a unique value per Paylocity Company ID.  **Allowable Values:**  10 char max
    * @type {string}
    * @memberof SensitiveDataApiAddOrUpdateEmployeeSensitiveData
    */
    readonly employeeId: string
    
} & SensitiveData

/**
 * Request parameters for getEmployeeSensitiveData operation in SensitiveDataApi.
 * @export
 * @interface SensitiveDataApiGetEmployeeSensitiveDataRequest
 */
export type SensitiveDataApiGetEmployeeSensitiveDataRequest = {
    
    /**
    * The Paylocity Company Identifier. This is the unique value provided by Paylocity to each specific Payroll Entity.                  **Allowable Values:**                  9 char max
    * @type {string}
    * @memberof SensitiveDataApiGetEmployeeSensitiveData
    */
    readonly companyId: string
    
    /**
    * The Paylocity Employee ID. This is a unique value per Paylocity Company ID.  **Allowable Values:**  10 char max
    * @type {string}
    * @memberof SensitiveDataApiGetEmployeeSensitiveData
    */
    readonly employeeId: string
    
}

/**
 * SensitiveDataApiGenerated - object-oriented interface
 * @export
 * @class SensitiveDataApiGenerated
 * @extends {BaseAPI}
 */
export class SensitiveDataApiGenerated extends BaseAPI {
    /**
     * Sends new or updated employee sensitive data information directly to Paylocity Payroll/HR solution.
     * @summary Add/update sensitive data
     * @param {SensitiveDataApiAddOrUpdateEmployeeSensitiveDataRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SensitiveDataApiGenerated
     */
    public addOrUpdateEmployeeSensitiveData(requestParameters: SensitiveDataApiAddOrUpdateEmployeeSensitiveDataRequest, options?: AxiosRequestConfig) {
        return SensitiveDataApiFp(this.configuration).addOrUpdateEmployeeSensitiveData(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Gets employee sensitive data information directly from Paylocity Payroll/HR solution.
     * @summary Get sensitive data
     * @param {SensitiveDataApiGetEmployeeSensitiveDataRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SensitiveDataApiGenerated
     */
    public getEmployeeSensitiveData(requestParameters: SensitiveDataApiGetEmployeeSensitiveDataRequest, options?: AxiosRequestConfig) {
        return SensitiveDataApiFp(this.configuration).getEmployeeSensitiveData(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
