/*
WebLink API

For documentation about this API, please visit https://developer.paylocity.com/integrations/reference/weblink-overview

The version of the OpenAPI document: v2
Contact: webservices@paylocity.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The Add Client Secret Request Model
 * @export
 * @interface AddClientSecret
 */
export interface AddClientSecret {
    /**
     * A value sent with the \'ACTION NEEDED: Web Link API Credentials Expiring Soon.\' email notification.
     * @type {string}
     * @memberof AddClientSecret
     */
    'code': string;
}

