/*
WebLink API

For documentation about this API, please visit https://developer.paylocity.com/integrations/reference/weblink-overview

The version of the OpenAPI document: v2
Contact: webservices@paylocity.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The benefit setup model
 * @export
 * @interface BenefitSetup
 */
export interface BenefitSetup {
    /**
     * Benefit Class code. Values are configured in Paylocity Payroll/HR solution Company > Setup > Benefits > Classes.<br  />Max length: 30
     * @type {object}
     * @memberof BenefitSetup
     */
    'benefitClass'?: object;
    /**
     * Date when Benefit Class takes effect. Common formats include *MM-DD-CCYY*, *CCYY-MM-DD*.
     * @type {object}
     * @memberof BenefitSetup
     */
    'benefitClassEffectiveDate'?: object;
    /**
     * Salary used to configure benefits.<br  />Decimal(12,2)
     * @type {object}
     * @memberof BenefitSetup
     */
    'benefitSalary'?: object;
    /**
     * Date when Benefit Salary takes effect. Common formats include *MM-DD-CCYY*, *CCYY-MM-DD*.
     * @type {object}
     * @memberof BenefitSetup
     */
    'benefitSalaryEffectiveDate'?: object;
    /**
     * Applicable only for HR Enhanced clients and Benefit Classes with ACA Employment Type of Full Time.
     * @type {object}
     * @memberof BenefitSetup
     */
    'doNotApplyAdministrativePeriod'?: object;
    /**
     * Only valid for HR Enhanced clients and Benefit Classes that are ACA Employment Type of Full Time.
     * @type {object}
     * @memberof BenefitSetup
     */
    'isMeasureAcaEligibility'?: object;
}

