/*
WebLink API

For documentation about this API, please visit https://developer.paylocity.com/integrations/reference/weblink-overview

The version of the OpenAPI document: v2
Contact: webservices@paylocity.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The Company Codes model
 * @export
 * @interface CompanyCodes
 */
export interface CompanyCodes {
    /**
     * Description. <br  /> Max length: 150
     * @type {object}
     * @memberof CompanyCodes
     */
    'description'?: object;
    /**
     * Code.<br  /> Max length: 40
     * @type {object}
     * @memberof CompanyCodes
     */
    'code'?: object;
}

