/*
WebLink API

For documentation about this API, please visit https://developer.paylocity.com/integrations/reference/weblink-overview

The version of the OpenAPI document: v2
Contact: webservices@paylocity.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CustomFieldDefinitionValuesInner
 */
export interface CustomFieldDefinitionValuesInner {
    /**
     * The custom field description.
     * @type {string}
     * @memberof CustomFieldDefinitionValuesInner
     */
    'description'?: string;
    /**
     * The custom field code.
     * @type {string}
     * @memberof CustomFieldDefinitionValuesInner
     */
    'code'?: string;
}

