/*
WebLink API

For documentation about this API, please visit https://developer.paylocity.com/integrations/reference/weblink-overview

The version of the OpenAPI document: v2
Contact: webservices@paylocity.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Deduction
 */
export interface Deduction {
    /**
     * Used to produce third-party checks for a specific agency. Must match Company setup.<br  />Max length: 5
     * @type {string}
     * @memberof Deduction
     */
    'agency'?: string;
    /**
     * Year to Date dollar amount not to be exceeded for a deduction in the calendar year. <br  />Decimal(12,2)
     * @type {number}
     * @memberof Deduction
     */
    'annualMaximum'?: number;
    /**
     * Defines how deductions are calculated. Common values are *% (percentage of gross), flat (flat dollar amount)*. Defaulted to the Company setup calcCode for deduction. <br  />Max length: 15
     * @type {string}
     * @memberof Deduction
     */
    'calcCode'?: string;
    /**
     * Child Support Case Identifier number, case number or court order number.<br  />Max length: 20
     * @type {string}
     * @memberof Deduction
     */
    'caseNo'?: string;
    /**
     * Cost Center associated with deduction. Must match Company setup.<br  /> Max length: 10
     * @type {string}
     * @memberof Deduction
     */
    'costCenter1'?: string;
    /**
     * Cost Center associated with deduction. Must match Company setup.<br  /> Max length: 10
     * @type {string}
     * @memberof Deduction
     */
    'costCenter2'?: string;
    /**
     * Cost Center associated with deduction. Must match Company setup.<br  /> Max length: 10
     * @type {string}
     * @memberof Deduction
     */
    'costCenter3'?: string;
    /**
     * Deduction code. Must match Company setup. <br  />Max length: 5
     * @type {string}
     * @memberof Deduction
     */
    'dcode'?: string;
    /**
     * Date deduction or benefit is active. Defaulted to run date or check date based on Company setup. Common formats are MM-DD-CCYY, CCYY-MM-DD
     * @type {string}
     * @memberof Deduction
     */
    'effectiveDate'?: string;
    /**
     * Stop date of a deduction or benefit. Common formats are MM-DD-CCYY, CCYY-MM-DD.
     * @type {string}
     * @memberof Deduction
     */
    'endDate'?: string;
    /**
     * Child support Federal Information Process Standard (FIPS) code. <br  />Max length: 7
     * @type {string}
     * @memberof Deduction
     */
    'fipsCode'?: string;
    /**
     * Needed if deduction is applied differently from the payroll frequency (one time deduction for example).<br  /> Max length: 5
     * @type {string}
     * @memberof Deduction
     */
    'frequency'?: string;
    /**
     * Dollar amount. The employee deduction will stop when the goal amount is reached.<br  /> Decimal(12,2)
     * @type {number}
     * @memberof Deduction
     */
    'goal'?: number;
    /**
     * Used for ACA. If not entered, defaulted to Company deduction setup
     * @type {boolean}
     * @memberof Deduction
     */
    'isSelfInsuredPlan'?: boolean;
    /**
     * 401K loan first payment date. Common formats are MM-DD-CCYY, CCYY-MM-DD
     * @type {string}
     * @memberof Deduction
     */
    'loanFirstPaymentDate401K'?: string;
    /**
     * 401K loan issue date. Common formats are MM-DD-CCYY, CCYY-MM-DD
     * @type {string}
     * @memberof Deduction
     */
    'loanIssueDate401K'?: string;
    /**
     * 401K Loan number, required for 401K Loan deduction types. <br  /> Max length: 50
     * @type {string}
     * @memberof Deduction
     */
    'loanNumber'?: string;
    /**
     * Maximum amount of the deduction on a single paycheck. <br  /> Decimal(12,2)
     * @type {number}
     * @memberof Deduction
     */
    'maximum'?: number;
    /**
     * Indicates if the employee qualifies for medical benefits that can be used to cover the child
     * @type {boolean}
     * @memberof Deduction
     */
    'medicalSupport'?: boolean;
    /**
     * Minimum amount of the deduction on a single paycheck. <br  /> Decimal(12,2)
     * @type {number}
     * @memberof Deduction
     */
    'minimum'?: number;
    /**
     * Information to print on the check stub if agency check is set up for this deduction. <br  />Max length: 50
     * @type {string}
     * @memberof Deduction
     */
    'miscInfo'?: string;
    /**
     * Amount already paid toward goal.<br  /> Decimal(12,2)
     * @type {number}
     * @memberof Deduction
     */
    'paidTowardsGoal'?: number;
    /**
     * Priority of a deduction within the deduction category. Common values are *0,1,2. <br  /> Max length: 2
     * @type {number}
     * @memberof Deduction
     */
    'priority'?: number;
    /**
     * Value to match the calcCode (percentage or amount). For example if calcCode = %, enter 10.00 to indicate 10%. <br  /> Decimal(12,2)
     * @type {number}
     * @memberof Deduction
     */
    'rate'?: number;
    /**
     * Indicates whether agency needs to be reported on terminated employee
     * @type {boolean}
     * @memberof Deduction
     */
    'reportTerminated'?: boolean;
    /**
     * Start date of a deduction based on payroll calendar. Common formats are MM-DD-CCYY, CCYY-MM-DD
     * @type {string}
     * @memberof Deduction
     */
    'startDate'?: string;
    /**
     * State for child support.<br  /> Max length: 2
     * @type {string}
     * @memberof Deduction
     */
    'stateAbbrev'?: string;
}

