/*
WebLink API

For documentation about this API, please visit https://developer.paylocity.com/integrations/reference/weblink-overview

The version of the OpenAPI document: v2
Contact: webservices@paylocity.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface DepartmentPosition
 */
export interface DepartmentPosition {
    /**
     * Employee department/position change reason. Must match Company setup.<br  />Max length: 15
     * @type {string}
     * @memberof DepartmentPosition
     */
    'changeReason'?: string;
    /**
     * Employee clock badge number. Deafults to employeeId. <br  />Max length: 10
     * @type {string}
     * @memberof DepartmentPosition
     */
    'clockBadgeNumber'?: string;
    /**
     * Employer defined location, like *branch, division, department*, etc. Must match Company setup. <br  />Max length: 10
     * @type {string}
     * @memberof DepartmentPosition
     */
    'costCenter1'?: string;
    /**
     * Employer defined location, like *branch, division, department*, etc. Must match Company setup. <br  />Max length: 10
     * @type {string}
     * @memberof DepartmentPosition
     */
    'costCenter2'?: string;
    /**
     * Employer defined location, like *branch, division, department*, etc. Must match Company setup. <br  />Max length: 10
     * @type {string}
     * @memberof DepartmentPosition
     */
    'costCenter3'?: string;
    /**
     * The date the position takes effect. (MM-DD-CCYY)
     * @type {string}
     * @memberof DepartmentPosition
     */
    'effectiveDate'?: string;
    /**
     * Employee current employment type. Common values *RFT (Regular Full Time), RPT (Regular Part Time), SNL (Seasonal), TFT (Temporary Full Time), TPT (Temporary Part Time)*. <br  />Max length: 10
     * @type {string}
     * @memberof DepartmentPosition
     */
    'employeeType'?: string;
    /**
     * Values are configured in Company > Setup > HR > EEO Classes.<br  /> Max length: 10
     * @type {string}
     * @memberof DepartmentPosition
     */
    'equalEmploymentOpportunityClass'?: string;
    /**
     * Indicates if employee is a supervisor or reviewer.
     * @type {boolean}
     * @memberof DepartmentPosition
     */
    'isSupervisorReviewer'?: boolean;
    /**
     * Employee current job title. <br  />Max length: 50
     * @type {string}
     * @memberof DepartmentPosition
     */
    'jobTitle'?: string;
    /**
     * Indicates if employee is exempt from minimum wage.
     * @type {boolean}
     * @memberof DepartmentPosition
     */
    'minimumWageExempt'?: boolean;
    /**
     * Indicates if employee is exempt from overtime.
     * @type {boolean}
     * @memberof DepartmentPosition
     */
    'overtimeExempt'?: boolean;
    /**
     * Employee pay group. Must match Company setup. <br  /> Max length: 20
     * @type {string}
     * @memberof DepartmentPosition
     */
    'payGroup'?: string;
    /**
     * Employee position code. Must match Company setup.<br  />Max length: 20
     * @type {string}
     * @memberof DepartmentPosition
     */
    'positionCode'?: string;
    /**
     * Employee work shift.<br  />Max length: 255
     * @type {string}
     * @memberof DepartmentPosition
     */
    'shift'?: string;
    /**
     * Supervisor\'s company number. Defaults to employee company number.<br  />Max length: 9
     * @type {string}
     * @memberof DepartmentPosition
     */
    'supervisorCompanyNumber'?: string;
    /**
     * EmployeeId of the supervisor. <br  />Max length: 10
     * @type {string}
     * @memberof DepartmentPosition
     */
    'supervisorEmployeeId'?: string;
    /**
     * Indicates if employee receives tips.
     * @type {string}
     * @memberof DepartmentPosition
     */
    'tipped'?: string;
    /**
     * Employee union affiliation effective date. Common formats are *MM-DD-CCYY, CCYY-MM-DD*.
     * @type {string}
     * @memberof DepartmentPosition
     */
    'unionAffiliationDate'?: string;
    /**
     * Employee union code. Must match Company setup. <br  />Max length: 10
     * @type {string}
     * @memberof DepartmentPosition
     */
    'unionCode'?: string;
    /**
     * Indicates if union dues are collected.
     * @type {boolean}
     * @memberof DepartmentPosition
     */
    'unionDuesCollected'?: boolean;
    /**
     * Indicates if union initiation fees are collected
     * @type {boolean}
     * @memberof DepartmentPosition
     */
    'unionInitiationCollected'?: boolean;
    /**
     * Employee union position. Must match Company setup. <br  />Max length: 30
     * @type {string}
     * @memberof DepartmentPosition
     */
    'unionPosition'?: string;
    /**
     * Employee worker compensation code. Must match Company setup.<br  /> Max length: 10
     * @type {string}
     * @memberof DepartmentPosition
     */
    'workersComp'?: string;
}

