/*
WebLink API

For documentation about this API, please visit https://developer.paylocity.com/integrations/reference/weblink-overview

The version of the OpenAPI document: v2
Contact: webservices@paylocity.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The EmployeeId Response Model
 * @export
 * @interface EmployeeIdResponse
 */
export interface EmployeeIdResponse {
    /**
     * The EmployeeId
     * @type {string}
     * @memberof EmployeeIdResponse
     */
    'employeeId'?: string;
}

