/*
WebLink API

For documentation about this API, please visit https://developer.paylocity.com/integrations/reference/weblink-overview

The version of the OpenAPI document: v2
Contact: webservices@paylocity.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Employee Status
 * @export
 * @interface EmployeeV1EmployeeStatus
 */
export interface EmployeeV1EmployeeStatus {
    /**
     * Employee current work status. Common values are *A* (Active), *L* (Leave of Absence), *T* (Terminated). <br  />Max length: 20
     * @type {string}
     * @memberof EmployeeV1EmployeeStatus
     */
    'employeeStatusCode'?: string;
}

