/*
WebLink API

For documentation about this API, please visit https://developer.paylocity.com/integrations/reference/weblink-overview

The version of the OpenAPI document: v2
Contact: webservices@paylocity.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { NewEmployee } from './new-employee';

/**
 * 
 * @export
 * @interface EmployeeV1CreateNewEmployeeRecordRequest
 */
export interface EmployeeV1CreateNewEmployeeRecordRequest {
    /**
     * 
     * @type {NewEmployee}
     * @memberof EmployeeV1CreateNewEmployeeRecordRequest
     */
    'newEmployee'?: NewEmployee;
}

