/*
WebLink API

For documentation about this API, please visit https://developer.paylocity.com/integrations/reference/weblink-overview

The version of the OpenAPI document: v2
Contact: webservices@paylocity.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Primary Pay Rate
 * @export
 * @interface EmployeeV1PrimaryPayRate
 */
export interface EmployeeV1PrimaryPayRate {
    /**
     * Employee annual salary. <br  />Decimal (12,2)
     * @type {number}
     * @memberof EmployeeV1PrimaryPayRate
     */
    'annualSalary'?: number;
    /**
     * Employee base rate, used for Hourly employees. <br  />Decimal (12,2)
     * @type {number}
     * @memberof EmployeeV1PrimaryPayRate
     */
    'baseRate'?: number;
    /**
     * Employee default hours consistently worked. If autoPayType is set to D, employee will be paid hourly base rate for the defaultHours. <br  />Decimal (12,2)
     * @type {number}
     * @memberof EmployeeV1PrimaryPayRate
     */
    'defaultHours'?: number;
    /**
     * Employee current pay frequency. Common values are *A (Annual), B (Bi-Weekly), D (Daily), M (Monthly), S (Semi-Monthly), Q (Quarterly), W (Weekly)*. <br  />Max length: 5
     * @type {string}
     * @memberof EmployeeV1PrimaryPayRate
     */
    'payFrequency'?: string;
    /**
     * Employee pay type (rate code). Valid values are *Hourly* or *Salary*. <br  />Max length: 10
     * @type {string}
     * @memberof EmployeeV1PrimaryPayRate
     */
    'payType'?: string;
    /**
     * The date the employee’s pay rate takes effect. (MM-DD-CCYY)
     * @type {string}
     * @memberof EmployeeV1PrimaryPayRate
     */
    'primaryPayRateEffectiveDate'?: string;
    /**
     * Employee gross salary per pay period used with payType Salary.<br  />Decimal (12,2)
     * @type {number}
     * @memberof EmployeeV1PrimaryPayRate
     */
    'salary'?: number;
}

