/*
WebLink API

For documentation about this API, please visit https://developer.paylocity.com/integrations/reference/weblink-overview

The version of the OpenAPI document: v2
Contact: webservices@paylocity.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EmployeeV1BenefitSetup } from './employee-v1-benefit-setup';
import { EmployeeV1DepartmentPosition } from './employee-v1-department-position';
import { EmployeeV1EmployeeStatus } from './employee-v1-employee-status';
import { EmployeeV1PrimaryPayRate } from './employee-v1-primary-pay-rate';

/**
 * Employee
 * @export
 * @interface EmployeeV1
 */
export interface EmployeeV1 {
    /**
     * Employee home 1st address line. <br  />Max length: 40
     * @type {string}
     * @memberof EmployeeV1
     */
    'address1'?: string;
    /**
     * Employee home 2nd address line. <br  />Max length: 40
     * @type {string}
     * @memberof EmployeeV1
     */
    'address2'?: string;
    /**
     * 
     * @type {EmployeeV1BenefitSetup}
     * @memberof EmployeeV1
     */
    'benefitSetup'?: EmployeeV1BenefitSetup;
    /**
     * Employee birthdate. Common formats are *MM-DD-CCYY, CCYY-MM-DD*.
     * @type {string}
     * @memberof EmployeeV1
     */
    'birthDate'?: string;
    /**
     * Employee home city. <br  />Max length: 40
     * @type {string}
     * @memberof EmployeeV1
     */
    'city'?: string;
    /**
     * Paylocity assigned company number. <br  /> Max length: 9
     * @type {string}
     * @memberof EmployeeV1
     */
    'companyNumber'?: string;
    /**
     * 
     * @type {EmployeeV1DepartmentPosition}
     * @memberof EmployeeV1
     */
    'departmentPosition'?: EmployeeV1DepartmentPosition;
    /**
     * Leave blank to have Paylocity Payroll/HR solution automatically assign the next available employee ID.<br  /> Max length: 10
     * @type {string}
     * @memberof EmployeeV1
     */
    'employeeId'?: string;
    /**
     * 
     * @type {EmployeeV1EmployeeStatus}
     * @memberof EmployeeV1
     */
    'employeeStatus'?: EmployeeV1EmployeeStatus;
    /**
     * Employee ethnicity.<br  /> Max length: 10
     * @type {string}
     * @memberof EmployeeV1
     */
    'ethnicity'?: string;
    /**
     * Employee first name. <br  />Max length: 40
     * @type {string}
     * @memberof EmployeeV1
     */
    'firstName'?: string;
    /**
     * Employee gender. Common values *M* (Male), *F* (Female). <br  />Max length: 1
     * @type {string}
     * @memberof EmployeeV1
     */
    'gender'?: string;
    /**
     * Indicates if employee meets the highly compensated employee criteria.
     * @type {boolean}
     * @memberof EmployeeV1
     */
    'highlyCompensatedEmployee'?: boolean;
    /**
     * Employee hired date. Common formats are *MM-DD-CCYY, CCYY-MM-DD*.
     * @type {string}
     * @memberof EmployeeV1
     */
    'hireDate'?: string;
    /**
     * Employee home phone number.  <br  />Max length: 12
     * @type {string}
     * @memberof EmployeeV1
     */
    'homePhone'?: string;
    /**
     * Employee last name. <br  />Max length: 40
     * @type {string}
     * @memberof EmployeeV1
     */
    'lastName'?: string;
    /**
     * Employee marital status. Common values *D (Divorced), M (Married), S (Single), W (Widowed)*. <br  />Max length: 10
     * @type {string}
     * @memberof EmployeeV1
     */
    'maritalStatus'?: string;
    /**
     * Employee middle name.<br  /> Max length: 20
     * @type {string}
     * @memberof EmployeeV1
     */
    'middleName'?: string;
    /**
     * Employee preferred display name. <br  /> Max length: 20
     * @type {string}
     * @memberof EmployeeV1
     */
    'nickname'?: string;
    /**
     * Percentage of employee\'s ownership in the company, entered as a whole number . <br  /> Decimal (12,2)
     * @type {number}
     * @memberof EmployeeV1
     */
    'ownerPercent'?: number;
    /**
     * Employee personal email address. <br  />Max length: 50
     * @type {string}
     * @memberof EmployeeV1
     */
    'personalEmailAddress'?: string;
    /**
     * Employee personal mobile phone number. <br  />Max length: 12
     * @type {string}
     * @memberof EmployeeV1
     */
    'personalMobilePhone'?: string;
    /**
     * Employee position code. Must match Company setup.<br  />Max length: 20 
     * @type {string}
     * @memberof EmployeeV1
     */
    'position'?: string;
    /**
     * Employee work zip code.<br  /> Max length: 10
     * @type {string}
     * @memberof EmployeeV1
     */
    'postalCode'?: string;
    /**
     * 
     * @type {EmployeeV1PrimaryPayRate}
     * @memberof EmployeeV1
     */
    'primaryPayRate'?: EmployeeV1PrimaryPayRate;
    /**
     * Rehire date if employee is rehired. Common formats are *MM-DD-CCYY, CCYY-MM-DD*.
     * @type {string}
     * @memberof EmployeeV1
     */
    'reHireDate'?: string;
    /**
     * Employee social security number. Leave it blank if valid social security number not available. <br  />Max length: 11
     * @type {string}
     * @memberof EmployeeV1
     */
    'ssn'?: string;
    /**
     * Employee home state. <br  />Max length: 2
     * @type {string}
     * @memberof EmployeeV1
     */
    'state'?: string;
    /**
     * Indicates if employee is statutory.
     * @type {boolean}
     * @memberof EmployeeV1
     */
    'statutory'?: boolean;
    /**
     * Supervisor\'s company number. Defaults to employee company number.<br  />Max length: 9
     * @type {string}
     * @memberof EmployeeV1
     */
    'supervisorCompanyNumber'?: string;
    /**
     * EmployeeId of the supervisor. <br  />Max length: 10
     * @type {string}
     * @memberof EmployeeV1
     */
    'supervisorEmployeeId'?: string;
    /**
     * Employee tax form for reporting income. Valid values are *W2, 1099M, 1099R*. Default is W2. <br  />Max length: 15
     * @type {string}
     * @memberof EmployeeV1
     */
    'taxForm'?: string;
    /**
     * Date of emplyee termination. Common formats are *MM-DD-CCYY, CCYY-MM-DD*.
     * @type {string}
     * @memberof EmployeeV1
     */
    'terminationDate'?: string;
    /**
     * Employee termination reason. Must match Company setup for employee status.<br  />Max length: 15
     * @type {string}
     * @memberof EmployeeV1
     */
    'terminationReason'?: string;
    /**
     * Employee work email. <br  />Max length: 50
     * @type {string}
     * @memberof EmployeeV1
     */
    'workEmailAddress'?: string;
    /**
     * Employee work phone number.<br  /> Max length: 12
     * @type {string}
     * @memberof EmployeeV1
     */
    'workPhone'?: string;
    /**
     * Employee work phone extension number.<br  /> Max length: 10
     * @type {string}
     * @memberof EmployeeV1
     */
    'workPhoneExt'?: string;
}

