/*
WebLink API

For documentation about this API, please visit https://developer.paylocity.com/integrations/reference/weblink-overview

The version of the OpenAPI document: v2
Contact: webservices@paylocity.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The employee model
 * @export
 * @interface Employee
 */
export interface Employee {
    /**
     * Add up to 19 direct deposit accounts in addition to the main direct deposit account. IMPORTANT: A direct deposit update will remove ALL existing main and additional direct deposit information in WebPay and replace with information provided on the request. GET API will not return direct deposit data.
     * @type {Array<object>}
     * @memberof Employee
     */
    'additionalDirectDeposit'?: Array<object>;
    /**
     * Add Additional Rates.
     * @type {Array<object>}
     * @memberof Employee
     */
    'additionalRate'?: Array<object>;
    /**
     *  Add or update setup values used for employee benefits integration, insurance plan settings, and ACA reporting.
     * @type {object}
     * @memberof Employee
     */
    'benefitSetup'?: object;
    /**
     * Employee birthdate. Common formats include *MM-DD-CCYY*, *CCYY-MM-DD*.
     * @type {object}
     * @memberof Employee
     */
    'birthDate'?: object;
    /**
     * Company FEIN as defined in Paylocity Payroll/HR solution, applicable with GET requests only.<br  /> Max length: 20
     * @type {object}
     * @memberof Employee
     */
    'companyFEIN'?: object;
    /**
     * Company name as defined in Paylocity Payroll/HR solution, applicable with GET requests only.<br  /> Max length: 50
     * @type {object}
     * @memberof Employee
     */
    'companyName'?: object;
    /**
     * Employee is paid in this currency. <br  />Max length: 30
     * @type {object}
     * @memberof Employee
     */
    'currency'?: object;
    /**
     * Up to 8 custom fields of boolean (checkbox) type value.
     * @type {Array<object>}
     * @memberof Employee
     */
    'customBooleanFields'?: Array<object>;
    /**
     * Up to 8 custom fields of the date type value.
     * @type {Array<object>}
     * @memberof Employee
     */
    'customDateFields'?: Array<object>;
    /**
     * Up to 8 custom fields of the dropdown type value.
     * @type {Array<object>}
     * @memberof Employee
     */
    'customDropDownFields'?: Array<object>;
    /**
     * Up to 8 custom fields of numeric type value.
     * @type {Array<object>}
     * @memberof Employee
     */
    'customNumberFields'?: Array<object>;
    /**
     * Up to 8 custom fields of text type value.
     * @type {Array<object>}
     * @memberof Employee
     */
    'customTextFields'?: Array<object>;
    /**
     * Add or update home department cost center, position, supervisor, reviewer, employment type, EEO class, pay settings, and union information.
     * @type {object}
     * @memberof Employee
     */
    'departmentPosition'?: object;
    /**
     * Indicates if employee has disability status.
     * @type {object}
     * @memberof Employee
     */
    'disabilityDescription'?: object;
    /**
     * Add or update Emergency Contacts.
     * @type {Array<object>}
     * @memberof Employee
     */
    'emergencyContacts'?: Array<object>;
    /**
     * Leave blank to have Paylocity Payroll/HR solution automatically assign the next available employee ID.<br  />Max length: 10
     * @type {object}
     * @memberof Employee
     */
    'employeeId'?: object;
    /**
     * Employee ethnicity.<br  /> Max length: 10
     * @type {object}
     * @memberof Employee
     */
    'ethnicity'?: object;
    /**
     * Add or update federal tax amount type (taxCalculationCode), amount or percentage, filing status, and exemptions.
     * @type {object}
     * @memberof Employee
     */
    'federalTax'?: object;
    /**
     * Employee first name. <br  />Max length: 40
     * @type {object}
     * @memberof Employee
     */
    'firstName'?: object;
    /**
     * Employee gender. Common values *M* (Male), *F* (Female). <br  />Max length: 1
     * @type {object}
     * @memberof Employee
     */
    'gender'?: object;
    /**
     * Add or update employee\'s home address, personal phone numbers, and personal email.
     * @type {object}
     * @memberof Employee
     */
    'homeAddress'?: object;
    /**
     * Indicates if employee meets the highly compensated employee criteria.
     * @type {boolean}
     * @memberof Employee
     */
    'isHighlyCompensated'?: boolean;
    /**
     * Indicates if employee is a smoker.
     * @type {boolean}
     * @memberof Employee
     */
    'isSmoker'?: boolean;
    /**
     * Employee last name. <br  />Max length: 40
     * @type {object}
     * @memberof Employee
     */
    'lastName'?: object;
    /**
     * Add, update, or delete local tax code, filing status, and exemptions including  PA-PSD taxes.
     * @type {Array<object>}
     * @memberof Employee
     */
    'localTax'?: Array<object>;
    /**
     * Add the main direct deposit account. After deposits are made to any additional direct deposit accounts, the remaining net check is deposited in the main direct deposit account. IMPORTANT: A direct deposit update will remove ALL existing main and additional direct deposit information in WebPay and replace with what is provided on the request. GET API will not return direct deposit data.
     * @type {object}
     * @memberof Employee
     */
    'mainDirectDeposit'?: object;
    /**
     * Employee marital status. Common values *D (Divorced), M (Married), S (Single), W (Widowed)*. <br  />Max length: 10
     * @type {object}
     * @memberof Employee
     */
    'maritalStatus'?: object;
    /**
     * Employee middle name.<br  /> Max length: 20
     * @type {object}
     * @memberof Employee
     */
    'middleName'?: object;
    /**
     * Add or update non-primary state tax code, amount type (taxCalculationCode), amount or percentage, filing status, exemptions, supplemental check (specialCheckCalc), and reciprocity code information.
     * @type {object}
     * @memberof Employee
     */
    'nonPrimaryStateTax'?: object;
    /**
     * Percentage of employee\'s ownership in the company, entered as a whole number. <br  /> Decimal (12,2)
     * @type {object}
     * @memberof Employee
     */
    'ownerPercent'?: object;
    /**
     * Employee preferred display name.<br  /> Max length: 20
     * @type {object}
     * @memberof Employee
     */
    'preferredName'?: object;
    /**
     * Add or update hourly or salary pay rate, effective date, and pay frequency.
     * @type {object}
     * @memberof Employee
     */
    'primaryPayRate'?: object;
    /**
     * Add or update primary state tax code, amount type (taxCalculationCode), amount or percentage, filing status, exemptions, and supplemental check (specialCheckCalc) information. Only one primary state is allowed. Sending an updated primary state will replace the current primary state.
     * @type {object}
     * @memberof Employee
     */
    'primaryStateTax'?: object;
    /**
     * Prior last name if applicable.<br  />Max length: 40
     * @type {object}
     * @memberof Employee
     */
    'priorLastName'?: object;
    /**
     * Employee preferred salutation. <br  />Max length: 10
     * @type {object}
     * @memberof Employee
     */
    'salutation'?: object;
    /**
     * Employee social security number. Leave it blank if valid social security number not available. <br  />Max length: 11
     * @type {object}
     * @memberof Employee
     */
    'ssn'?: object;
    /**
     * Add or update employee status, change reason, effective date, and adjusted seniority date. Note that companies that are still in Implementation cannot hire future employees.
     * @type {object}
     * @memberof Employee
     */
    'status'?: object;
    /**
     * Employee name suffix. Common values are *Jr, Sr, II*.<br  />Max length: 30
     * @type {object}
     * @memberof Employee
     */
    'suffix'?: object;
    /**
     * Add tax form, 1099 exempt reasons and notes, and 943 agricultural employee information. Once the employee receives wages, this information cannot be updated. Add or update SUI tax state, retirement plan, and statutory information.
     * @type {object}
     * @memberof Employee
     */
    'taxSetup'?: object;
    /**
     * Indicates if employee is a veteran.
     * @type {object}
     * @memberof Employee
     */
    'veteranDescription'?: object;
    /**
     * Add or update Web Time badge number and charge rate and synchronize Paylocity Payroll/HR solution and Web Time employee data.
     * @type {object}
     * @memberof Employee
     */
    'webTime'?: object;
    /**
     * Add or update employee\'s work address, phone numbers, and email. Work Location drop down field is not included.
     * @type {object}
     * @memberof Employee
     */
    'workAddress'?: object;
    /**
     * Add or update I-9 work authorization information.
     * @type {object}
     * @memberof Employee
     */
    'workEligibility'?: object;
}

