/*
WebLink API

For documentation about this API, please visit https://developer.paylocity.com/integrations/reference/weblink-overview

The version of the OpenAPI document: v2
Contact: webservices@paylocity.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The error option model
 * @export
 * @interface ErrorOptionsInner
 */
export interface ErrorOptionsInner {
    /**
     * The description of the option.
     * @type {string}
     * @memberof ErrorOptionsInner
     */
    'description'?: string;
    /**
     * The code associated with this option.
     * @type {string}
     * @memberof ErrorOptionsInner
     */
    'code'?: string;
}

