/*
WebLink API

For documentation about this API, please visit https://developer.paylocity.com/integrations/reference/weblink-overview

The version of the OpenAPI document: v2
Contact: webservices@paylocity.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ErrorOptionsInner } from './error-options-inner';

/**
 * The error model
 * @export
 * @interface ModelError
 */
export interface ModelError {
    /**
     * The name of the field, or property in the request message that contains an error.
     * @type {string}
     * @memberof ModelError
     */
    'field'?: string;
    /**
     * The error message.
     * @type {string}
     * @memberof ModelError
     */
    'message'?: string;
    /**
     * A list of options associated with this error. These options may indicate valid values for the field, or property that contains an error.
     * @type {Array<ErrorOptionsInner>}
     * @memberof ModelError
     */
    'options'?: Array<ErrorOptionsInner>;
    /**
     * The JSON path of the field, or property, that contains an error in the request message.
     * @type {string}
     * @memberof ModelError
     */
    'path'?: string;
}

