/*
WebLink API

For documentation about this API, please visit https://developer.paylocity.com/integrations/reference/weblink-overview

The version of the OpenAPI document: v2
Contact: webservices@paylocity.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface NewLocalTax
 */
export interface NewLocalTax {
    /**
     * Local tax code.<br  />Max length: 50
     * @type {string}
     * @memberof NewLocalTax
     */
    'tCode'?: string;
    /**
     * Local tax exemptions value.<br  />Decimal (12,2)
     * @type {number}
     * @memberof NewLocalTax
     */
    'exemptions'?: number;
    /**
     * Local tax exemptions 2 value.<br  />Decimal (12,2)
     * @type {number}
     * @memberof NewLocalTax
     */
    'exemptions2'?: number;
    /**
     * Employee local tax filing status. Must match specific local tax setup. <br  /> Max length: 50
     * @type {string}
     * @memberof NewLocalTax
     */
    'filingStatus'?: string;
    /**
     * Resident PSD (political subdivision code) applicable in PA. Must match Company setup.<br  /> Max length: 9
     * @type {string}
     * @memberof NewLocalTax
     */
    'residentPSD'?: string;
    /**
     * Work location PSD. Must match Company setup. <br  /> Max length: 9
     * @type {string}
     * @memberof NewLocalTax
     */
    'workPSD'?: string;
}

