/*
WebLink API

For documentation about this API, please visit https://developer.paylocity.com/integrations/reference/weblink-overview

The version of the OpenAPI document: v2
Contact: webservices@paylocity.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface NewStateTax
 */
export interface NewStateTax {
    /**
     * State tax code.<br  /> Max length: 50
     * @type {number}
     * @memberof NewStateTax
     */
    'amount'?: number;
    /**
     * State tax exemptions value.<br  />Decimal (12,2)
     * @type {number}
     * @memberof NewStateTax
     */
    'exemptions'?: number;
    /**
     * State tax exemptions 2 value.<br  />Decimal (12,2)
     * @type {number}
     * @memberof NewStateTax
     */
    'exemptions2'?: number;
    /**
     * Employee state tax filing status. Common values are *S* (Single), *M* (Married).<br  />Max length: 50
     * @type {string}
     * @memberof NewStateTax
     */
    'filingStatus'?: string;
    /**
     * Gross Wage Percentage value. <br  />Decimal (12,2)
     * @type {number}
     * @memberof NewStateTax
     */
    'grossWagePercentage'?: number;
    /**
     * State Tax percentage. <br  />Decimal (12,2)
     * @type {number}
     * @memberof NewStateTax
     */
    'percentage'?: number;
    /**
     * Indicates if primary tax.
     * @type {boolean}
     * @memberof NewStateTax
     */
    'primaryTax'?: boolean;
    /**
     * Indicates if state tax is reciprocal.
     * @type {string}
     * @memberof NewStateTax
     */
    'reciprocal'?: string;
    /**
     * Supplemental check calculation code. Common values are *Blocked* (Taxes blocked on Supplemental checks), *Supp* (Use supplemental Tax Rate-Code). <br  />Max length: 10
     * @type {string}
     * @memberof NewStateTax
     */
    'specialCheckCalc'?: string;
    /**
     * Tax calculation code. Common values are *F* (Flat), *P* (Percentage), *FDFP* (Flat Dollar Amount plus Fixed Percentage). <br  />Max length: 10
     * @type {string}
     * @memberof NewStateTax
     */
    'taxCalcCode'?: string;
    /**
     * State tax code.<br  /> Max length: 50
     * @type {string}
     * @memberof NewStateTax
     */
    'tCode'?: string;
}

