/*
WebLink API

For documentation about this API, please visit https://developer.paylocity.com/integrations/reference/weblink-overview

The version of the OpenAPI document: v2
Contact: webservices@paylocity.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { NewAdditionalDirectDeposit } from './new-additional-direct-deposit';
import { NewBenefitClassSetup } from './new-benefit-class-setup';
import { NewFedTax } from './new-fed-tax';
import { NewLocalTax } from './new-local-tax';
import { NewMainDirectDeposit } from './new-main-direct-deposit';
import { NewStateTax } from './new-state-tax';
import { NewWorkEligibility } from './new-work-eligibility';

/**
 * 
 * @export
 * @interface NewEmployee
 */
export interface NewEmployee {
    /**
     * Employee current job title.<br  />Max length: 50
     * @type {string}
     * @memberof NewEmployee
     */
    'title'?: string;
    /**
     * Employee home 1st address line. <br  />Max length: 40
     * @type {string}
     * @memberof NewEmployee
     */
    'address1'?: string;
    /**
     * Employee home 2nd address line. <br  />Max length: 40
     * @type {string}
     * @memberof NewEmployee
     */
    'address2'?: string;
    /**
     * Adjusted seniority date. Common formats are *MM-DD-CCYY, CCYY-MM-DD*.
     * @type {string}
     * @memberof NewEmployee
     */
    'adjSeniorityDate'?: string;
    /**
     * Employee annual salary. <br  />Decimal (12,2)
     * @type {number}
     * @memberof NewEmployee
     */
    'annualSalary'?: number;
    /**
     * *True* to have Paylocity Payroll/HR solution automatically assign the next available employee ID.<br  />*False* when providing a value in the employeeId field.
     * @type {boolean}
     * @memberof NewEmployee
     */
    'autoGenerateEmployeeId'?: boolean;
    /**
     * If set to *True*, employee will be paid automatically using deafultHours.
     * @type {boolean}
     * @memberof NewEmployee
     */
    'autoPay'?: boolean;
    /**
     * Valid values are *N, D, S*. (N- employee won\'t automatically receive a salary or hours during payroll, D - employee will be automatically paid in defaultHours during payroll, S - employee will be automatically paid Salary
     * @type {string}
     * @memberof NewEmployee
     */
    'autoPayType'?: string;
    /**
     * Employee base rate, used for Hourly employees. <br  />Decimal (12,2)
     * @type {number}
     * @memberof NewEmployee
     */
    'baseRate'?: number;
    /**
     * Employee birthdate. Common formats are *MM-DD-CCYY, CCYY-MM-DD*.
     * @type {string}
     * @memberof NewEmployee
     */
    'birthDate'?: string;
    /**
     * Employee home city. <br  />Max length: 40
     * @type {string}
     * @memberof NewEmployee
     */
    'city'?: string;
    /**
     * Employee clock badge number. Deafults to employeeId. <br  />Max length: 10
     * @type {string}
     * @memberof NewEmployee
     */
    'clockBadge'?: string;
    /**
     * Paylocity assigned company number.<br  /> Max length: 9
     * @type {string}
     * @memberof NewEmployee
     */
    'companyNumber': string;
    /**
     * Employer defined location, like *branch, division, department*, etc. Must match Company setup. <br  />Max length: 10
     * @type {string}
     * @memberof NewEmployee
     */
    'costCenter1'?: string;
    /**
     * Employer defined location, like *branch, division, department*, etc. Must match Company setup. <br  />Max length: 10
     * @type {string}
     * @memberof NewEmployee
     */
    'costCenter2'?: string;
    /**
     * Employer defined location, like *branch, division, department*, etc. Must match Company setup. <br  />Max length: 10
     * @type {string}
     * @memberof NewEmployee
     */
    'costCenter3'?: string;
    /**
     * Employee country. <br  /> Max length: 30
     * @type {string}
     * @memberof NewEmployee
     */
    'country'?: string;
    /**
     * Employee county.<br  /> Max length: 30 
     * @type {string}
     * @memberof NewEmployee
     */
    'county'?: string;
    /**
     * Employee default hours consistently worked. If autoPayType is set to D, employee will be paid hourly base rate for the defaultHours. <br  />Decimal (12,2)
     * @type {number}
     * @memberof NewEmployee
     */
    'defaultHours'?: number;
    /**
     * Indicates if employee has disability status.
     * @type {boolean}
     * @memberof NewEmployee
     */
    'disability'?: boolean;
    /**
     * Indicates if employee eligible for rehire.
     * @type {boolean}
     * @memberof NewEmployee
     */
    'eligibleForRehire'?: boolean;
    /**
     * Indicates if employee in agriculture or farming.
     * @type {boolean}
     * @memberof NewEmployee
     */
    'employee943'?: boolean;
    /**
     * Leave blank to have Paylocity Payroll/HR solution automatically assign the next available employee ID.<br  /> Max length: 10
     * @type {string}
     * @memberof NewEmployee
     */
    'employeeId'?: string;
    /**
     * Employee current work status. Common values are *A* (Active), *L* (Leave of Absence), *T* (Terminated). <br  />Max length: 20
     * @type {string}
     * @memberof NewEmployee
     */
    'employeeStatus'?: string;
    /**
     * Employee current employment type. Common values *RFT (Regular Full Time), RPT (Regular Part Time), SNL (Seasonal), TFT (Temporary Full Time), TPT (Temporary Part Time)*. <br  />Max length: 10
     * @type {string}
     * @memberof NewEmployee
     */
    'employmentType'?: string;
    /**
     * Values are configured in Company > Setup > HR > EEO Classes.<br  /> Max length: 10
     * @type {string}
     * @memberof NewEmployee
     */
    'equalEmploymentOpportunityClass'?: string;
    /**
     * Employee ethnicity.<br  /> Max length: 10
     * @type {string}
     * @memberof NewEmployee
     */
    'ethnicity'?: string;
    /**
     * Employee first name. <br  />Max length: 40
     * @type {string}
     * @memberof NewEmployee
     */
    'firstName'?: string;
    /**
     * Indicates if employee exempt from federal income tax.
     * @type {boolean}
     * @memberof NewEmployee
     */
    'fitwExempt'?: boolean;
    /**
     * Notes for FITW exempt.<br  /> Max length: 250
     * @type {string}
     * @memberof NewEmployee
     */
    'fitwExemptNotes'?: string;
    /**
     * Reason code for FITW exemption. Common values are *SE* (Statutory employee), *CR* (clergy/Religious). <br  /> Max length: 30
     * @type {string}
     * @memberof NewEmployee
     */
    'fitwExemptReason'?: string;
    /**
     * Indicates if employee is exempt from Federal Unemployment Tax Act.
     * @type {boolean}
     * @memberof NewEmployee
     */
    'futaExempt'?: boolean;
    /**
     * FUTA exempt note. <br  /> Max length: 250
     * @type {string}
     * @memberof NewEmployee
     */
    'futaExemptNotes'?: string;
    /**
     * Reason code for FUTA exemption. Common values are *501* (5019c)(3) Organization), *IC* (Independent Contractor).<br  /> Max length: 30
     * @type {string}
     * @memberof NewEmployee
     */
    'futaExemptReason'?: string;
    /**
     * Employee hired date. Common formats are *MM-DD-CCYY, CCYY-MM-DD*.
     * @type {string}
     * @memberof NewEmployee
     */
    'hireDate'?: string;
    /**
     * Employee home phone number.<br  />Max length: 12
     * @type {string}
     * @memberof NewEmployee
     */
    'homePhone'?: string;
    /**
     * Indicates if employee is a supervisor or reviewer.
     * @type {boolean}
     * @memberof NewEmployee
     */
    'isSupervisorReviewer'?: boolean;
    /**
     * Employee last name. <br  />Max length: 40
     * @type {string}
     * @memberof NewEmployee
     */
    'lastName'?: string;
    /**
     * Employee marital status. Common values *D (Divorced), M (Married), S (Single), W (Widowed)*. <br  />Max length: 10
     * @type {string}
     * @memberof NewEmployee
     */
    'maritalStatus'?: string;
    /**
     * Indicates if employee is Medicare exempt.
     * @type {boolean}
     * @memberof NewEmployee
     */
    'medExempt'?: boolean;
    /**
     * Notes for Medicare exempt.
     * @type {string}
     * @memberof NewEmployee
     */
    'medExemptNotes'?: string;
    /**
     * Reason code for Medicare exemption. Common values are *501* (5019c)(3) Organization), *IC* (Independent Contractor).<br  /> Max length: 30
     * @type {string}
     * @memberof NewEmployee
     */
    'medExemptReason'?: string;
    /**
     * Employee middle name.<br  /> Max length: 20
     * @type {string}
     * @memberof NewEmployee
     */
    'middleName'?: string;
    /**
     * Indicates if employee is exempt from minimum wage.
     * @type {boolean}
     * @memberof NewEmployee
     */
    'minimumWageExempt'?: boolean;
    /**
     * Employee preferred display name.<br  /> Max length: 20
     * @type {string}
     * @memberof NewEmployee
     */
    'nickname'?: string;
    /**
     * Indicates override to the default Job Title. Use the title field to enter Employee job title.
     * @type {boolean}
     * @memberof NewEmployee
     */
    'overrideTitle'?: boolean;
    /**
     * Indicates if employee is exempt from overtime.
     * @type {boolean}
     * @memberof NewEmployee
     */
    'overtimeExempt'?: boolean;
    /**
     * Employee current pay frequency. Common values are *A (Annual), B (Bi-Weekly), D (Daily), M (Monthly), S (Semi-Monthly), Q (Quarterly), W (Weekly)*. <br  />Max length: 5
     * @type {string}
     * @memberof NewEmployee
     */
    'payFrequency'?: string;
    /**
     * Employee pay grade. Must match Company setup. <br  /> Max length: 10
     * @type {string}
     * @memberof NewEmployee
     */
    'payGrade'?: string;
    /**
     * Employee pay group. Must match Company setup. <br  /> Max length: 20
     * @type {string}
     * @memberof NewEmployee
     */
    'payGroup'?: string;
    /**
     * Pay rate notes regarding employee.<br  /> Max length: 250
     * @type {string}
     * @memberof NewEmployee
     */
    'payRateNote'?: string;
    /**
     * Indicates if employee is eligible for pension.
     * @type {boolean}
     * @memberof NewEmployee
     */
    'pension'?: boolean;
    /**
     * Employee personal email address. <br  />Max length: 50
     * @type {string}
     * @memberof NewEmployee
     */
    'personalEmailAddress'?: string;
    /**
     * Employee personal mobile phone number. <br  />Max length: 12
     * @type {string}
     * @memberof NewEmployee
     */
    'personalMobilePhone'?: string;
    /**
     * Employee position code. Must match Company setup.<br  />Max length: 20
     * @type {string}
     * @memberof NewEmployee
     */
    'positionCode'?: string;
    /**
     * Primary Pay Rate EffectiveDate
     * @type {string}
     * @memberof NewEmployee
     */
    'primaryPayRateEffectiveDate'?: string;
    /**
     * Prior last name if applicable.<br  />Max length: 40
     * @type {string}
     * @memberof NewEmployee
     */
    'priorLastName'?: string;
    /**
     * Employee rate (pay type) code.  Valid values are *Hourly* or *Salary*. <br  />Max length: 10
     * @type {string}
     * @memberof NewEmployee
     */
    'rateCode'?: string;
    /**
     * Employee base rate frequency used with payType Hourly. Common values are *Hour, Week*. Default is Hour. <br  />Max length: 10
     * @type {string}
     * @memberof NewEmployee
     */
    'ratePer'?: string;
    /**
     * Company number of reviewer. <br  />Max length: 9
     * @type {string}
     * @memberof NewEmployee
     */
    'reviewerCo'?: string;
    /**
     * Employee id of the reviewer. <br  />Max length: 10
     * @type {string}
     * @memberof NewEmployee
     */
    'reviewerId'?: string;
    /**
     * Employee gross salary per pay period used with payType Salary.<br  />Decimal (12,2)
     * @type {number}
     * @memberof NewEmployee
     */
    'salary'?: number;
    /**
     * Employee preferred salutation. <br  />Max length: 10
     * @type {string}
     * @memberof NewEmployee
     */
    'salutation'?: string;
    /**
     * Employee gender. Common values *M* (Male), *F* (Female). <br  />Max length: 1
     * @type {string}
     * @memberof NewEmployee
     */
    'sex'?: string;
    /**
     * Employee work shift.<br  />Max length: 255
     * @type {string}
     * @memberof NewEmployee
     */
    'shift'?: string;
    /**
     * Indicates if employee exempt from state income tax.
     * @type {boolean}
     * @memberof NewEmployee
     */
    'sitwExempt'?: boolean;
    /**
     * Notes for SITW exempt.<br  /> Max length: 250
     * @type {string}
     * @memberof NewEmployee
     */
    'sitwExemptNotes'?: string;
    /**
     * Reason code for SITW exemption. Common values are *SE* (Statutory employee), *CR* (clergy/Religious). <br  /> Max length: 30
     * @type {string}
     * @memberof NewEmployee
     */
    'sitwExemptReason'?: string;
    /**
     * Indicates if employee is a smoker.
     * @type {boolean}
     * @memberof NewEmployee
     */
    'smoker'?: boolean;
    /**
     * Indicates if employee is exempt from Social Security taxes.
     * @type {boolean}
     * @memberof NewEmployee
     */
    'ssExempt'?: boolean;
    /**
     * Notes for Socal Security exemptions.<br  /> Max length: 250
     * @type {string}
     * @memberof NewEmployee
     */
    'ssExemptNotes'?: string;
    /**
     * Reason code for Social Security exemption. Common values are *SE* (Statutory employee), *CR* (clergy/Religious). <br  /> Max length: 30
     * @type {string}
     * @memberof NewEmployee
     */
    'ssExemptReason'?: string;
    /**
     * Employee social security number. Leave it blank if valid social security number not available. <br  />Max length: 11
     * @type {string}
     * @memberof NewEmployee
     */
    'ssn'?: string;
    /**
     * Employee home state. <br  />Max length: 2
     * @type {string}
     * @memberof NewEmployee
     */
    'state'?: string;
    /**
     * Indicates if employee is statutory.
     * @type {boolean}
     * @memberof NewEmployee
     */
    'statutory'?: boolean;
    /**
     * Employee name suffix. Common values are *Jr, Sr, II*.<br  />Max length: 30
     * @type {string}
     * @memberof NewEmployee
     */
    'suffix'?: string;
    /**
     * Indicates if employee is exempt from state unemployment insurance.
     * @type {boolean}
     * @memberof NewEmployee
     */
    'suiExempt'?: boolean;
    /**
     * Notes for SUI exempt.<br  /> Max length: 250
     * @type {string}
     * @memberof NewEmployee
     */
    'suiExemptNotes'?: string;
    /**
     * Reason code for SUI exemption. Common values are *SE* (Statutory employee), *CR* (clergy/Religious). <br  /> Max length: 30
     * @type {string}
     * @memberof NewEmployee
     */
    'suiExemptReason'?: string;
    /**
     * Employee SUI (State Unemployment Insurance) state. <br  />Max length: 2
     * @type {string}
     * @memberof NewEmployee
     */
    'suiState'?: string;
    /**
     * Supervisor\'s company number. Defaults to employee company number.<br  />Max length: 9
     * @type {string}
     * @memberof NewEmployee
     */
    'supervisorCo'?: string;
    /**
     * EmployeeId of the supervisor. <br  />Max length: 10
     * @type {string}
     * @memberof NewEmployee
     */
    'supervisorID'?: string;
    /**
     * Emplopyee 1099R distribution code. Common values are *7* (Normal Distribution), *F* (Charitable Gift Annuity). <br  />Max length: 1
     * @type {string}
     * @memberof NewEmployee
     */
    'taxDistributionCode1099R'?: string;
    /**
     * Employee tax form for reporting income. Valid values are *W2, 1099M, 1099R*. Default is W2. <br  />Max length: 15
     * @type {string}
     * @memberof NewEmployee
     */
    'taxForm'?: string;
    /**
     * Indicates if employee receives tips.
     * @type {string}
     * @memberof NewEmployee
     */
    'tipped'?: string;
    /**
     * Employee union code. Must match Company setup. <br  />Max length: 10
     * @type {string}
     * @memberof NewEmployee
     */
    'unionCode'?: string;
    /**
     * Employee union affiliation effective date. Common formats are *MM-DD-CCYY, CCYY-MM-DD*.
     * @type {string}
     * @memberof NewEmployee
     */
    'unionDate'?: string;
    /**
     * Indicates if union dues are collected.
     * @type {boolean}
     * @memberof NewEmployee
     */
    'unionDues'?: boolean;
    /**
     * Indicates if initiations fees are collected.
     * @type {boolean}
     * @memberof NewEmployee
     */
    'unionInitFees'?: boolean;
    /**
     * Employee union position. Must match Company setup. <br  />Max length: 30
     * @type {string}
     * @memberof NewEmployee
     */
    'unionPosition'?: string;
    /**
     * Indicates if employee is a veteran.
     * @type {boolean}
     * @memberof NewEmployee
     */
    'veteran'?: boolean;
    /**
     * Indicates if employee is exempt from Washington state Liability Insurance.
     * @type {boolean}
     * @memberof NewEmployee
     */
    'waliExempt'?: boolean;
    /**
     * Notes for WALI exemption.
     * @type {string}
     * @memberof NewEmployee
     */
    'waliExemptNotes'?: string;
    /**
     * Reason code for WALI exemption. Common values are *SE* (Statutory employee), *CR* (clergy/Religious). <br  /> Max length: 30
     * @type {string}
     * @memberof NewEmployee
     */
    'waliExemptReason'?: string;
    /**
     * Employee work 1st address line.<br  /> Max length: 40
     * @type {string}
     * @memberof NewEmployee
     */
    'workAddress1'?: string;
    /**
     * Employee work 2nd address line. <br  /> Max length: 40
     * @type {string}
     * @memberof NewEmployee
     */
    'workAddress2'?: string;
    /**
     * Employee work city.<br  /> Max length: 40
     * @type {string}
     * @memberof NewEmployee
     */
    'workCity'?: string;
    /**
     * Employee work country.<br  /> Max length: 30
     * @type {string}
     * @memberof NewEmployee
     */
    'workCountry'?: string;
    /**
     * Employee work county.<br  /> Max length: 30
     * @type {string}
     * @memberof NewEmployee
     */
    'workCounty'?: string;
    /**
     * Employee work email. <br  />Max length: 50
     * @type {string}
     * @memberof NewEmployee
     */
    'workEmailAddress'?: string;
    /**
     * Employee worker compensation code. Must match Company setup.<br  /> Max length: 10
     * @type {string}
     * @memberof NewEmployee
     */
    'workersComp'?: string;
    /**
     * Employee work phone extension number.<br  /> Max length: 10
     * @type {string}
     * @memberof NewEmployee
     */
    'workExt'?: string;
    /**
     * Employee work location. <br  /> Max length: 50
     * @type {string}
     * @memberof NewEmployee
     */
    'workLocation'?: string;
    /**
     * Employee physical mail box location.<br  /> Max length: 10
     * @type {string}
     * @memberof NewEmployee
     */
    'workMailStop'?: string;
    /**
     * Employee work mobile phone number.<br  /> Max length: 12
     * @type {string}
     * @memberof NewEmployee
     */
    'workMobilePhone'?: string;
    /**
     * Employee work pager number.<br  /> Max length: 20
     * @type {string}
     * @memberof NewEmployee
     */
    'workPager'?: string;
    /**
     * Employee work phone number.<br  /> Max length: 12
     * @type {string}
     * @memberof NewEmployee
     */
    'workPhone'?: string;
    /**
     * Employee work state.<br  /> Max length: 2
     * @type {string}
     * @memberof NewEmployee
     */
    'workState'?: string;
    /**
     * Employee work zip code.<br  /> Max length: 10
     * @type {string}
     * @memberof NewEmployee
     */
    'workZip'?: string;
    /**
     * Employee home zip code. <br  />Max length: 10
     * @type {string}
     * @memberof NewEmployee
     */
    'zip'?: string;
    /**
     * If set to *True*, employee will be synced with Web Time.
     * @type {boolean}
     * @memberof NewEmployee
     */
    'syncWebTimeRecord'?: boolean;
    /**
     * 
     * @type {Array<NewBenefitClassSetup>}
     * @memberof NewEmployee
     */
    'newBenefitClassSetup'?: Array<NewBenefitClassSetup>;
    /**
     * 
     * @type {Array<NewMainDirectDeposit>}
     * @memberof NewEmployee
     */
    'newMainDirectDeposit'?: Array<NewMainDirectDeposit>;
    /**
     * 
     * @type {Array<NewAdditionalDirectDeposit>}
     * @memberof NewEmployee
     */
    'newAdditionalDirectDeposit'?: Array<NewAdditionalDirectDeposit>;
    /**
     * 
     * @type {Array<NewFedTax>}
     * @memberof NewEmployee
     */
    'newFedTax'?: Array<NewFedTax>;
    /**
     * 
     * @type {Array<NewLocalTax>}
     * @memberof NewEmployee
     */
    'newLocalTax'?: Array<NewLocalTax>;
    /**
     * 
     * @type {Array<NewStateTax>}
     * @memberof NewEmployee
     */
    'newStateTax'?: Array<NewStateTax>;
    /**
     * 
     * @type {Array<NewWorkEligibility>}
     * @memberof NewEmployee
     */
    'newWorkEligibility'?: Array<NewWorkEligibility>;
}

