/*
WebLink API

For documentation about this API, please visit https://developer.paylocity.com/integrations/reference/weblink-overview

The version of the OpenAPI document: v2
Contact: webservices@paylocity.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface NewFedTax
 */
export interface NewFedTax {
    /**
     * Tax amount. <br  />Decimal (12,2)
     * @type {number}
     * @memberof NewFedTax
     */
    'amount'?: number;
    /**
     * Federal tax exemptions value. <br  />Decimal (12,2)
     * @type {number}
     * @memberof NewFedTax
     */
    'exemptions'?: number;
    /**
     * Employee federal filing status. Common values are *S* (Single), *M* (Married).<br  />Max length: 50
     * @type {string}
     * @memberof NewFedTax
     */
    'filingStatus'?: string;
    /**
     * Tax percentage. <br  />Decimal (12,2)
     * @type {number}
     * @memberof NewFedTax
     */
    'percentage'?: number;
    /**
     * Tax calculation code. Common values are *F* (Flat), *P* (Percentage), *FDFP* (Flat Dollar Amount plus Fixed Percentage). <br  />Max length: 10
     * @type {string}
     * @memberof NewFedTax
     */
    'taxCalcCode'?: string;
    /**
     * Tax code. <br  /> Max length: 50
     * @type {string}
     * @memberof NewFedTax
     */
    'tCode'?: string;
}

