/*
WebLink API

For documentation about this API, please visit https://developer.paylocity.com/integrations/reference/weblink-overview

The version of the OpenAPI document: v2
Contact: webservices@paylocity.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The pay statement summary model
 * @export
 * @interface PayStatementSummary
 */
export interface PayStatementSummary {
    /**
     * .<br />
     * @type {boolean}
     * @memberof PayStatementSummary
     */
    'autoPay'?: boolean;
    /**
     * .<br />
     * @type {object}
     * @memberof PayStatementSummary
     */
    'beginDate'?: object;
    /**
     * .<br />
     * @type {object}
     * @memberof PayStatementSummary
     */
    'checkDate'?: object;
    /**
     * .<br />
     * @type {number}
     * @memberof PayStatementSummary
     */
    'checkNumber'?: number;
    /**
     * .<br />
     * @type {object}
     * @memberof PayStatementSummary
     */
    'directDepositAmount'?: object;
    /**
     * .<br />
     * @type {object}
     * @memberof PayStatementSummary
     */
    'endDate'?: object;
    /**
     * .<br />
     * @type {object}
     * @memberof PayStatementSummary
     */
    'grossPay'?: object;
    /**
     * .<br />
     * @type {object}
     * @memberof PayStatementSummary
     */
    'hours'?: object;
    /**
     * .<br />
     * @type {object}
     * @memberof PayStatementSummary
     */
    'netCheck'?: object;
    /**
     * .<br />
     * @type {object}
     * @memberof PayStatementSummary
     */
    'netPay'?: object;
    /**
     * .<br />
     * @type {object}
     * @memberof PayStatementSummary
     */
    'overtimeDollars'?: object;
    /**
     * .<br />
     * @type {object}
     * @memberof PayStatementSummary
     */
    'overtimeHours'?: object;
    /**
     * .<br />
     * @type {number}
     * @memberof PayStatementSummary
     */
    'process'?: number;
    /**
     * .<br />
     * @type {object}
     * @memberof PayStatementSummary
     */
    'regularDollars'?: object;
    /**
     * .<br />
     * @type {object}
     * @memberof PayStatementSummary
     */
    'regularHours'?: object;
    /**
     * <br />
     * @type {number}
     * @memberof PayStatementSummary
     */
    'transactionNumber'?: number;
    /**
     * .<br />
     * @type {number}
     * @memberof PayStatementSummary
     */
    'voucherNumber'?: number;
    /**
     * .<br />
     * @type {object}
     * @memberof PayStatementSummary
     */
    'workersCompCode'?: object;
    /**
     * .<br />
     * @type {number}
     * @memberof PayStatementSummary
     */
    'year'?: number;
}

