/*
WebLink API

For documentation about this API, please visit https://developer.paylocity.com/integrations/reference/weblink-overview

The version of the OpenAPI document: v2
Contact: webservices@paylocity.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The pay statement details model
 * @export
 * @interface PayStatementDetails
 */
export interface PayStatementDetails {
    /**
     * .<br />
     * @type {object}
     * @memberof PayStatementDetails
     */
    'amount'?: object;
    /**
     * .<br />
     * @type {object}
     * @memberof PayStatementDetails
     */
    'checkDate'?: object;
    /**
     * .<br />
     * @type {object}
     * @memberof PayStatementDetails
     */
    'det'?: object;
    /**
     * .<br />
     * @type {object}
     * @memberof PayStatementDetails
     */
    'detCode'?: object;
    /**
     * .<br />
     * @type {object}
     * @memberof PayStatementDetails
     */
    'detType'?: object;
    /**
     * .<br />
     * @type {object}
     * @memberof PayStatementDetails
     */
    'eligibleCompensation'?: object;
    /**
     * .<br />
     * @type {object}
     * @memberof PayStatementDetails
     */
    'hours'?: object;
    /**
     * .<br />
     * @type {object}
     * @memberof PayStatementDetails
     */
    'rate'?: object;
    /**
     * <br />
     * @type {number}
     * @memberof PayStatementDetails
     */
    'transactionNumber'?: number;
    /**
     * .<br />
     * @type {object}
     * @memberof PayStatementDetails
     */
    'transactionType'?: object;
    /**
     * .<br />
     * @type {number}
     * @memberof PayStatementDetails
     */
    'year'?: number;
}

