/*
WebLink API

For documentation about this API, please visit https://developer.paylocity.com/integrations/reference/weblink-overview

The version of the OpenAPI document: v2
Contact: webservices@paylocity.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PrimaryPayRate
 */
export interface PrimaryPayRate {
    /**
     * If set to *True*, employee will be paid automatically using deafultHours. 
     * @type {boolean}
     * @memberof PrimaryPayRate
     */
    'autoPay'?: boolean;
    /**
     * Employee base rate, used for Hourly employees. <br  />Decimal (12,2)
     * @type {number}
     * @memberof PrimaryPayRate
     */
    'baseRate'?: number;
    /**
     * Employee default hours consistently worked. If autoPayType is set to D, employee will be paid hourly base rate for the defaultHours. <br  />Decimal (12,2)
     * @type {number}
     * @memberof PrimaryPayRate
     */
    'defaultHours'?: number;
    /**
     * The date the employee’s pay rate takes effect. Common formats are *MM-DD-CCYY, CCYY-MM-DD*.
     * @type {string}
     * @memberof PrimaryPayRate
     */
    'effectiveDate'?: string;
    /**
     * Employee current pay frequency. Common values are *A (Annual), B (Bi-Weekly), D (Daily), M (Monthly), S (Semi-Monthly), Q (Quarterly), W (Weekly)*. <br  />Max length: 5
     * @type {string}
     * @memberof PrimaryPayRate
     */
    'payFrequency'?: string;
    /**
     * Employee pay grade. Must match Company setup. <br  /> Max length: 10
     * @type {string}
     * @memberof PrimaryPayRate
     */
    'payGrade'?: string;
    /**
     * Employee pay type (rate code). Valid values are *Hourly* or *Salary*. <br  />Max length: 10
     * @type {string}
     * @memberof PrimaryPayRate
     */
    'payType'?: string;
    /**
     * Employee base rate frequency used with payType Hourly. Common values are *Hour, Week*. Default is Hour. <br  />Max length: 10
     * @type {string}
     * @memberof PrimaryPayRate
     */
    'ratePer'?: string;
    /**
     * Primary Pay Rate change reason. Must match Company setup.<br  />Max length: 15
     * @type {string}
     * @memberof PrimaryPayRate
     */
    'reason'?: string;
    /**
     * Employee gross salary per pay period used with payType Salary.<br  />Decimal (12,2)
     * @type {number}
     * @memberof PrimaryPayRate
     */
    'salary'?: number;
}

