/*
WebLink API

For documentation about this API, please visit https://developer.paylocity.com/integrations/reference/weblink-overview

The version of the OpenAPI document: v2
Contact: webservices@paylocity.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The State Tax model
 * @export
 * @interface StateTax
 */
export interface StateTax {
    /**
     * State tax code.<br  /> Max length: 50
     * @type {object}
     * @memberof StateTax
     */
    'amount'?: object;
    /**
     * Box 4(b) on form W4 (year 2020 or later): Deductions amount. <br  />Decimal (12,2)
     * @type {number}
     * @memberof StateTax
     */
    'deductionsAmount'?: number;
    /**
     * Box 3 on form W4 (year 2020 or later): Total dependents amount. <br  />Decimal (12,2)
     * @type {number}
     * @memberof StateTax
     */
    'dependentsAmount'?: number;
    /**
     * State tax exemptions value.<br  />Decimal (12,2)
     * @type {object}
     * @memberof StateTax
     */
    'exemptions'?: object;
    /**
     * State tax exemptions 2 value.<br  />Decimal (12,2)
     * @type {object}
     * @memberof StateTax
     */
    'exemptions2'?: object;
    /**
     * Employee state tax filing status. Common values are *S* (Single), *M* (Married).<br  />Max length: 50
     * @type {object}
     * @memberof StateTax
     */
    'filingStatus'?: object;
    /**
     * Box 2(c) on form W4 (year 2020 or later): Multiple Jobs or Spouse Works. <br  />Boolean
     * @type {boolean}
     * @memberof StateTax
     */
    'higherRate'?: boolean;
    /**
     * Box 4(a) on form W4 (year 2020 or later): Other income amount. <br  />Decimal (12,2)
     * @type {number}
     * @memberof StateTax
     */
    'otherIncomeAmount'?: number;
    /**
     * State Tax percentage. <br  />Decimal (12,2)
     * @type {object}
     * @memberof StateTax
     */
    'percentage'?: object;
    /**
     * Supplemental check calculation code. Common values are *Blocked* (Taxes blocked on Supplemental checks), *Supp* (Use supplemental Tax Rate-Code). <br  />Max length: 10
     * @type {object}
     * @memberof StateTax
     */
    'specialCheckCalc'?: object;
    /**
     * Tax calculation code. Common values are *F* (Flat), *P* (Percentage), *FDFP* (Flat Dollar Amount plus Fixed Percentage). <br  />Max length: 10
     * @type {object}
     * @memberof StateTax
     */
    'taxCalculationCode'?: object;
    /**
     * State tax code.<br  /> Max length: 50
     * @type {object}
     * @memberof StateTax
     */
    'taxCode'?: object;
    /**
     * The state W4 form year <br  />Integer
     * @type {number}
     * @memberof StateTax
     */
    'w4FormYear'?: number;
}

