/*
WebLink API

For documentation about this API, please visit https://developer.paylocity.com/integrations/reference/weblink-overview

The version of the OpenAPI document: v2
Contact: webservices@paylocity.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The Tracking Number Response model
 * @export
 * @interface TrackingNumberResponse
 */
export interface TrackingNumberResponse {
    /**
     * The unique tracking number
     * @type {string}
     * @memberof TrackingNumberResponse
     */
    'trackingNumber'?: string;
}

