/*
WebLink API

For documentation about this API, please visit https://developer.paylocity.com/integrations/reference/weblink-overview

The version of the OpenAPI document: v2
Contact: webservices@paylocity.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BenefitSetup } from './benefit-setup';
import { DepartmentPosition } from './department-position';
import { PrimaryPayRate } from './primary-pay-rate';
import { WebTime } from './web-time';

/**
 * 
 * @export
 * @interface UpdateEmployee
 */
export interface UpdateEmployee {
    /**
     * Employee home 1st address line. <br  />Max length: 40
     * @type {string}
     * @memberof UpdateEmployee
     */
    'address1'?: string;
    /**
     * Employee home 2nd address line. <br  />Max length: 40
     * @type {string}
     * @memberof UpdateEmployee
     */
    'address2'?: string;
    /**
     * Adjusted seniority date. Common formats are *MM-DD-CCYY, CCYY-MM-DD*.
     * @type {string}
     * @memberof UpdateEmployee
     */
    'adjSeniorityDate'?: string;
    /**
     * Employee birthdate. Common formats are *MM-DD-CCYY, CCYY-MM-DD*.
     * @type {string}
     * @memberof UpdateEmployee
     */
    'birthDate'?: string;
    /**
     * Employee home city. <br  />Max length: 40
     * @type {string}
     * @memberof UpdateEmployee
     */
    'city'?: string;
    /**
     * Paylocity assigned company number. <br  /> Max length: 9
     * @type {string}
     * @memberof UpdateEmployee
     */
    'companyNumber'?: string;
    /**
     * Employee country. <br  /> Max length: 30
     * @type {string}
     * @memberof UpdateEmployee
     */
    'country'?: string;
    /**
     * Employee county.<br  /> Max length: 30
     * @type {string}
     * @memberof UpdateEmployee
     */
    'county'?: string;
    /**
     * Indicates if employee has disability status.
     * @type {string}
     * @memberof UpdateEmployee
     */
    'disability'?: string;
    /**
     * Indicates if employee eligible for rehire.
     * @type {boolean}
     * @memberof UpdateEmployee
     */
    'eligibleForRehire'?: boolean;
    /**
     * The Paylocity Employee ID. This is a unique value per Paylocity Company ID.  **Allowable Values:**  10 char max
     * @type {string}
     * @memberof UpdateEmployee
     */
    'employeeId'?: string;
    /**
     * Employee current work status. Common values are *A* (Active), *L* (Leave of Absence), *T* (Terminated). <br  />Max length: 20
     * @type {string}
     * @memberof UpdateEmployee
     */
    'employeeStatus'?: string;
    /**
     * Employee status change reason. Must match Company setup.<br  />Max length: 15
     * @type {string}
     * @memberof UpdateEmployee
     */
    'empStatusChangeReason'?: string;
    /**
     * Effective date of employee status change, can be in the future. Common formats are *MM-DD-CCYY, CCYY-MM-DD*.
     * @type {string}
     * @memberof UpdateEmployee
     */
    'empStatusEffectiveDate'?: string;
    /**
     * Employee ethnicity.<br  /> Max length: 10
     * @type {string}
     * @memberof UpdateEmployee
     */
    'ethnicity'?: string;
    /**
     * Employee first name. <br  />Max length: 40
     * @type {string}
     * @memberof UpdateEmployee
     */
    'firstName'?: string;
    /**
     * Employee home phone number.  <br  />Max length: 12
     * @type {string}
     * @memberof UpdateEmployee
     */
    'homePhone'?: string;
    /**
     * Employee last name. <br  />Max length: 40
     * @type {string}
     * @memberof UpdateEmployee
     */
    'lastName'?: string;
    /**
     * Employee marital status. Common values *D (Divorced), M (Married), S (Single), W (Widowed)*. <br  />Max length: 10
     * @type {string}
     * @memberof UpdateEmployee
     */
    'maritalStatus'?: string;
    /**
     * Employee middle name.<br  /> Max length: 20
     * @type {string}
     * @memberof UpdateEmployee
     */
    'middleName'?: string;
    /**
     * Employee preferred display name. <br  /> Max length: 20
     * @type {string}
     * @memberof UpdateEmployee
     */
    'nickname'?: string;
    /**
     * Employee work pager number.<br  /> Max length: 20
     * @type {string}
     * @memberof UpdateEmployee
     */
    'pager'?: string;
    /**
     * Employee personal email address. <br  />Max length: 50
     * @type {string}
     * @memberof UpdateEmployee
     */
    'personalEmailAddress'?: string;
    /**
     * Employee personal mobile phone number. <br  />Max length: 12
     * @type {string}
     * @memberof UpdateEmployee
     */
    'personalMobilePhone'?: string;
    /**
     * Prior last name if applicable.<br  />Max length: 40
     * @type {string}
     * @memberof UpdateEmployee
     */
    'priorLastName'?: string;
    /**
     * Employee preferred salutation. <br  />Max length: 10
     * @type {string}
     * @memberof UpdateEmployee
     */
    'salutation'?: string;
    /**
     * Employee gender. Common values *M* (Male), *F* (Female). <br  />Max length: 1
     * @type {string}
     * @memberof UpdateEmployee
     */
    'sex'?: string;
    /**
     * Indicates if employee is a smoker.
     * @type {boolean}
     * @memberof UpdateEmployee
     */
    'smoker'?: boolean;
    /**
     * Employee social security number. Leave it blank if valid social security number not available. <br  />Max length: 11
     * @type {string}
     * @memberof UpdateEmployee
     */
    'ssn'?: string;
    /**
     * Employee home state. <br  />Max length: 2
     * @type {string}
     * @memberof UpdateEmployee
     */
    'state'?: string;
    /**
     * Employee name suffix. Common values are *Jr, Sr, II*.<br  />Max length: 30
     * @type {string}
     * @memberof UpdateEmployee
     */
    'suffix'?: string;
    /**
     * Indicates if employee is exempt from state unemployment insurance.
     * @type {boolean}
     * @memberof UpdateEmployee
     */
    'suiExempt'?: boolean;
    /**
     * Notes for SUI exempt.<br  /> Max length: 250
     * @type {string}
     * @memberof UpdateEmployee
     */
    'suiExemptNotes'?: string;
    /**
     * Reason code for SUI exemption. Common values are *SE* (Statutory employee), *CR* (Clergy/Religious). <br  /> Max length: 30
     * @type {string}
     * @memberof UpdateEmployee
     */
    'suiExemptReason'?: string;
    /**
     * Indicates if employee is a veteran.
     * @type {string}
     * @memberof UpdateEmployee
     */
    'veteran'?: string;
    /**
     * Employee work 1st address line.<br  /> Max length: 40
     * @type {string}
     * @memberof UpdateEmployee
     */
    'workAddress1'?: string;
    /**
     * Employee work 2nd address line. <br  /> Max length: 40
     * @type {string}
     * @memberof UpdateEmployee
     */
    'workAddress2'?: string;
    /**
     * Employee work city.<br  /> Max length: 40
     * @type {string}
     * @memberof UpdateEmployee
     */
    'workCity'?: string;
    /**
     * Employee work country.<br  /> Max length: 30
     * @type {string}
     * @memberof UpdateEmployee
     */
    'workCountry'?: string;
    /**
     * Employee work county.<br  /> Max length: 30
     * @type {string}
     * @memberof UpdateEmployee
     */
    'workCounty'?: string;
    /**
     * Employee work email. <br  />Max length: 50
     * @type {string}
     * @memberof UpdateEmployee
     */
    'workEmailAddress'?: string;
    /**
     * Employee physical mail box location.<br  /> Max length: 10
     * @type {string}
     * @memberof UpdateEmployee
     */
    'workMailStop'?: string;
    /**
     * Employee work mobile phone number.<br  /> Max length: 12
     * @type {string}
     * @memberof UpdateEmployee
     */
    'workMobilePhone'?: string;
    /**
     * Employee work pager number.<br  /> Max length: 20
     * @type {string}
     * @memberof UpdateEmployee
     */
    'workPager'?: string;
    /**
     * Employee work phone number.<br  /> Max length: 12
     * @type {string}
     * @memberof UpdateEmployee
     */
    'workPhone'?: string;
    /**
     * Employee work phone extension number.<br  /> Max length: 10
     * @type {string}
     * @memberof UpdateEmployee
     */
    'workPhoneExt'?: string;
    /**
     * Employee work state.<br  /> Max length: 2
     * @type {string}
     * @memberof UpdateEmployee
     */
    'workState'?: string;
    /**
     * Employee work zip code.<br  /> Max length: 10
     * @type {string}
     * @memberof UpdateEmployee
     */
    'workZip'?: string;
    /**
     * Employee home zip code. <br  />Max length: 10
     * @type {string}
     * @memberof UpdateEmployee
     */
    'zip'?: string;
    /**
     * 
     * @type {Array<BenefitSetup>}
     * @memberof UpdateEmployee
     */
    'benefitSetup'?: Array<BenefitSetup>;
    /**
     * 
     * @type {Array<DepartmentPosition>}
     * @memberof UpdateEmployee
     */
    'departmentPosition'?: Array<DepartmentPosition>;
    /**
     * 
     * @type {Array<PrimaryPayRate>}
     * @memberof UpdateEmployee
     */
    'primaryPayRate'?: Array<PrimaryPayRate>;
    /**
     * 
     * @type {Array<WebTime>}
     * @memberof UpdateEmployee
     */
    'webTime'?: Array<WebTime>;
}

